select
    organization_id,
    inventory_item_id,
    vendor_serial_number,
    serial_number,
    current_subinventory_code,
    serial_num_status,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    created_by,
    to_timestamp(to_char(creation_date,'YYYY/MM/DD HH24:MI:SS'),'YYYY/MM/DD HH24:MI:SS') creation_date,
    last_updated_by,
    to_timestamp(to_char(last_update_date,'YYYY/MM/DD HH24:MI:SS'),'YYYY/MM/DD HH24:MI:SS') last_update_date,
    inventory_item,
    inventory_descrription,
    unit_meas_lookup_code,
    uom_code,
    inventory_item_status_code,
    xx_expiryproduct,
    category_code,
    category_description,
    inv_structure_id,
    inv_category_id,
    inv_category_code,
    inv_category_description,
    proc_structure_id,
    proc_category_id,
    proc_category_code,
    proc_category_description,
    to_date(to_char(sysdate,'YYYY/MM/DD'),'YYYY/MM/DD') AS snapshot_dt,
    to_timestamp(substr('{data_interval_end}',1,26),'YYYY-MM-DD HH24:MI:SS.FF6') as processing_dttm 
from xx_erpsms_onhand_sn_v