name: organizations/11111111/customConstraints/custom.cloudbuildDisableWorkerPoolExternalIP
resourceTypes:
  - cloudbuild.googleapis.com/WorkerPool
methodTypes:
  - CREATE
  - UPDATE
condition: (resource.privatePoolV1Config.networkConfig.egressOption != "NO_PUBLIC_EGRESS")
actionType: DENY
displayName: Deny unauthorized worker pools external ip used for each build
description: Ensure no unauthorized worker pools external ip used for each build
