severity: MEDIUM
description: Detect if a log buckets have retention periods and regionalization that are not configured as per the security policy
recommendation: Ensure all log buckets have retention periods and regionalization configured as per the security policy
resource_selector:
  resource_types:
  - logging.googleapis.com/LogBucket
predicate:
  expression: (!has(resource.retentionDays) || !["asia-southeast1", "asia-southeast2"].exists(loc, resource.name.contains("/locations/" + loc + "/")))
