// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

public interface CPUMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.example.CPUMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cpu = 1;</code>
   */
  java.lang.String getCpu();
  /**
   * <code>string cpu = 1;</code>
   */
  com.google.protobuf.ByteString
      getCpuBytes();

  /**
   * <code>float usage_user = 2;</code>
   */
  float getUsageUser();

  /**
   * <code>float usage_system = 3;</code>
   */
  float getUsageSystem();

  /**
   * <code>float usage_idle = 4;</code>
   */
  float getUsageIdle();

  /**
   * <code>int32 usage_irq = 5;</code>
   */
  int getUsageIrq();

  /**
   * <code>float usage_softirq = 6;</code>
   */
  float getUsageSoftirq();

  /**
   * <code>int32 usage_steal = 7;</code>
   */
  int getUsageSteal();

  /**
   * <code>int32 usage_nice = 8;</code>
   */
  int getUsageNice();

  /**
   * <code>int32 usage_iowait = 9;</code>
   */
  int getUsageIowait();

  /**
   * <code>float usage_guest = 10;</code>
   */
  float getUsageGuest();

  /**
   * <code>int32 usage_guest_nice = 11;</code>
   */
  int getUsageGuestNice();
}
