// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

/**
 * Protobuf type {@code google.protobuf.example.HostMetrics}
 */
public  final class HostMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.example.HostMetrics)
    HostMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HostMetrics.newBuilder() to construct.
  private HostMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HostMetrics() {
    net_ = java.util.Collections.emptyList();
    net2_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HostMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.cloud.example.protobuf.DiskMetrics.Builder subBuilder = null;
            if (disk_ != null) {
              subBuilder = disk_.toBuilder();
            }
            disk_ = input.readMessage(com.google.cloud.example.protobuf.DiskMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(disk_);
              disk_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.cloud.example.protobuf.DiskIOMetrics.Builder subBuilder = null;
            if (diskio_ != null) {
              subBuilder = diskio_.toBuilder();
            }
            diskio_ = input.readMessage(com.google.cloud.example.protobuf.DiskIOMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(diskio_);
              diskio_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.cloud.example.protobuf.SystemMetrics.Builder subBuilder = null;
            if (systemMetrics_ != null) {
              subBuilder = systemMetrics_.toBuilder();
            }
            systemMetrics_ = input.readMessage(com.google.cloud.example.protobuf.SystemMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(systemMetrics_);
              systemMetrics_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.cloud.example.protobuf.CPUMetrics.Builder subBuilder = null;
            if (cpuMetrics_ != null) {
              subBuilder = cpuMetrics_.toBuilder();
            }
            cpuMetrics_ = input.readMessage(com.google.cloud.example.protobuf.CPUMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cpuMetrics_);
              cpuMetrics_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              net_ = new java.util.ArrayList<com.google.cloud.example.protobuf.NetMetrics>();
              mutable_bitField0_ |= 0x00000010;
            }
            net_.add(
                input.readMessage(com.google.cloud.example.protobuf.NetMetrics.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              net2_ = new java.util.ArrayList<com.google.cloud.example.protobuf.NetMetrics2>();
              mutable_bitField0_ |= 0x00000020;
            }
            net2_.add(
                input.readMessage(com.google.cloud.example.protobuf.NetMetrics2.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        net_ = java.util.Collections.unmodifiableList(net_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        net2_ = java.util.Collections.unmodifiableList(net2_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_HostMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_HostMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.example.protobuf.HostMetrics.class, com.google.cloud.example.protobuf.HostMetrics.Builder.class);
  }

  private int bitField0_;
  public static final int DISK_FIELD_NUMBER = 1;
  private com.google.cloud.example.protobuf.DiskMetrics disk_;
  /**
   * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
   */
  public boolean hasDisk() {
    return disk_ != null;
  }
  /**
   * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
   */
  public com.google.cloud.example.protobuf.DiskMetrics getDisk() {
    return disk_ == null ? com.google.cloud.example.protobuf.DiskMetrics.getDefaultInstance() : disk_;
  }
  /**
   * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
   */
  public com.google.cloud.example.protobuf.DiskMetricsOrBuilder getDiskOrBuilder() {
    return getDisk();
  }

  public static final int DISKIO_FIELD_NUMBER = 2;
  private com.google.cloud.example.protobuf.DiskIOMetrics diskio_;
  /**
   * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
   */
  public boolean hasDiskio() {
    return diskio_ != null;
  }
  /**
   * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
   */
  public com.google.cloud.example.protobuf.DiskIOMetrics getDiskio() {
    return diskio_ == null ? com.google.cloud.example.protobuf.DiskIOMetrics.getDefaultInstance() : diskio_;
  }
  /**
   * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
   */
  public com.google.cloud.example.protobuf.DiskIOMetricsOrBuilder getDiskioOrBuilder() {
    return getDiskio();
  }

  public static final int SYSTEM_METRICS_FIELD_NUMBER = 3;
  private com.google.cloud.example.protobuf.SystemMetrics systemMetrics_;
  /**
   * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
   */
  public boolean hasSystemMetrics() {
    return systemMetrics_ != null;
  }
  /**
   * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
   */
  public com.google.cloud.example.protobuf.SystemMetrics getSystemMetrics() {
    return systemMetrics_ == null ? com.google.cloud.example.protobuf.SystemMetrics.getDefaultInstance() : systemMetrics_;
  }
  /**
   * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
   */
  public com.google.cloud.example.protobuf.SystemMetricsOrBuilder getSystemMetricsOrBuilder() {
    return getSystemMetrics();
  }

  public static final int CPU_METRICS_FIELD_NUMBER = 4;
  private com.google.cloud.example.protobuf.CPUMetrics cpuMetrics_;
  /**
   * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
   */
  public boolean hasCpuMetrics() {
    return cpuMetrics_ != null;
  }
  /**
   * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
   */
  public com.google.cloud.example.protobuf.CPUMetrics getCpuMetrics() {
    return cpuMetrics_ == null ? com.google.cloud.example.protobuf.CPUMetrics.getDefaultInstance() : cpuMetrics_;
  }
  /**
   * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
   */
  public com.google.cloud.example.protobuf.CPUMetricsOrBuilder getCpuMetricsOrBuilder() {
    return getCpuMetrics();
  }

  public static final int NET_FIELD_NUMBER = 5;
  private java.util.List<com.google.cloud.example.protobuf.NetMetrics> net_;
  /**
   * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
   */
  public java.util.List<com.google.cloud.example.protobuf.NetMetrics> getNetList() {
    return net_;
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
   */
  public java.util.List<? extends com.google.cloud.example.protobuf.NetMetricsOrBuilder> 
      getNetOrBuilderList() {
    return net_;
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
   */
  public int getNetCount() {
    return net_.size();
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
   */
  public com.google.cloud.example.protobuf.NetMetrics getNet(int index) {
    return net_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
   */
  public com.google.cloud.example.protobuf.NetMetricsOrBuilder getNetOrBuilder(
      int index) {
    return net_.get(index);
  }

  public static final int NET2_FIELD_NUMBER = 6;
  private java.util.List<com.google.cloud.example.protobuf.NetMetrics2> net2_;
  /**
   * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
   */
  public java.util.List<com.google.cloud.example.protobuf.NetMetrics2> getNet2List() {
    return net2_;
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
   */
  public java.util.List<? extends com.google.cloud.example.protobuf.NetMetrics2OrBuilder> 
      getNet2OrBuilderList() {
    return net2_;
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
   */
  public int getNet2Count() {
    return net2_.size();
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
   */
  public com.google.cloud.example.protobuf.NetMetrics2 getNet2(int index) {
    return net2_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
   */
  public com.google.cloud.example.protobuf.NetMetrics2OrBuilder getNet2OrBuilder(
      int index) {
    return net2_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (disk_ != null) {
      output.writeMessage(1, getDisk());
    }
    if (diskio_ != null) {
      output.writeMessage(2, getDiskio());
    }
    if (systemMetrics_ != null) {
      output.writeMessage(3, getSystemMetrics());
    }
    if (cpuMetrics_ != null) {
      output.writeMessage(4, getCpuMetrics());
    }
    for (int i = 0; i < net_.size(); i++) {
      output.writeMessage(5, net_.get(i));
    }
    for (int i = 0; i < net2_.size(); i++) {
      output.writeMessage(6, net2_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (disk_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDisk());
    }
    if (diskio_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDiskio());
    }
    if (systemMetrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSystemMetrics());
    }
    if (cpuMetrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCpuMetrics());
    }
    for (int i = 0; i < net_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, net_.get(i));
    }
    for (int i = 0; i < net2_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, net2_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.example.protobuf.HostMetrics)) {
      return super.equals(obj);
    }
    com.google.cloud.example.protobuf.HostMetrics other = (com.google.cloud.example.protobuf.HostMetrics) obj;

    boolean result = true;
    result = result && (hasDisk() == other.hasDisk());
    if (hasDisk()) {
      result = result && getDisk()
          .equals(other.getDisk());
    }
    result = result && (hasDiskio() == other.hasDiskio());
    if (hasDiskio()) {
      result = result && getDiskio()
          .equals(other.getDiskio());
    }
    result = result && (hasSystemMetrics() == other.hasSystemMetrics());
    if (hasSystemMetrics()) {
      result = result && getSystemMetrics()
          .equals(other.getSystemMetrics());
    }
    result = result && (hasCpuMetrics() == other.hasCpuMetrics());
    if (hasCpuMetrics()) {
      result = result && getCpuMetrics()
          .equals(other.getCpuMetrics());
    }
    result = result && getNetList()
        .equals(other.getNetList());
    result = result && getNet2List()
        .equals(other.getNet2List());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDisk()) {
      hash = (37 * hash) + DISK_FIELD_NUMBER;
      hash = (53 * hash) + getDisk().hashCode();
    }
    if (hasDiskio()) {
      hash = (37 * hash) + DISKIO_FIELD_NUMBER;
      hash = (53 * hash) + getDiskio().hashCode();
    }
    if (hasSystemMetrics()) {
      hash = (37 * hash) + SYSTEM_METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getSystemMetrics().hashCode();
    }
    if (hasCpuMetrics()) {
      hash = (37 * hash) + CPU_METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getCpuMetrics().hashCode();
    }
    if (getNetCount() > 0) {
      hash = (37 * hash) + NET_FIELD_NUMBER;
      hash = (53 * hash) + getNetList().hashCode();
    }
    if (getNet2Count() > 0) {
      hash = (37 * hash) + NET2_FIELD_NUMBER;
      hash = (53 * hash) + getNet2List().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.HostMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.example.protobuf.HostMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.example.HostMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.example.HostMetrics)
      com.google.cloud.example.protobuf.HostMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_HostMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_HostMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.example.protobuf.HostMetrics.class, com.google.cloud.example.protobuf.HostMetrics.Builder.class);
    }

    // Construct using com.google.cloud.example.protobuf.HostMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNetFieldBuilder();
        getNet2FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (diskBuilder_ == null) {
        disk_ = null;
      } else {
        disk_ = null;
        diskBuilder_ = null;
      }
      if (diskioBuilder_ == null) {
        diskio_ = null;
      } else {
        diskio_ = null;
        diskioBuilder_ = null;
      }
      if (systemMetricsBuilder_ == null) {
        systemMetrics_ = null;
      } else {
        systemMetrics_ = null;
        systemMetricsBuilder_ = null;
      }
      if (cpuMetricsBuilder_ == null) {
        cpuMetrics_ = null;
      } else {
        cpuMetrics_ = null;
        cpuMetricsBuilder_ = null;
      }
      if (netBuilder_ == null) {
        net_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        netBuilder_.clear();
      }
      if (net2Builder_ == null) {
        net2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        net2Builder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_HostMetrics_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.HostMetrics getDefaultInstanceForType() {
      return com.google.cloud.example.protobuf.HostMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.HostMetrics build() {
      com.google.cloud.example.protobuf.HostMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.HostMetrics buildPartial() {
      com.google.cloud.example.protobuf.HostMetrics result = new com.google.cloud.example.protobuf.HostMetrics(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (diskBuilder_ == null) {
        result.disk_ = disk_;
      } else {
        result.disk_ = diskBuilder_.build();
      }
      if (diskioBuilder_ == null) {
        result.diskio_ = diskio_;
      } else {
        result.diskio_ = diskioBuilder_.build();
      }
      if (systemMetricsBuilder_ == null) {
        result.systemMetrics_ = systemMetrics_;
      } else {
        result.systemMetrics_ = systemMetricsBuilder_.build();
      }
      if (cpuMetricsBuilder_ == null) {
        result.cpuMetrics_ = cpuMetrics_;
      } else {
        result.cpuMetrics_ = cpuMetricsBuilder_.build();
      }
      if (netBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          net_ = java.util.Collections.unmodifiableList(net_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.net_ = net_;
      } else {
        result.net_ = netBuilder_.build();
      }
      if (net2Builder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          net2_ = java.util.Collections.unmodifiableList(net2_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.net2_ = net2_;
      } else {
        result.net2_ = net2Builder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.example.protobuf.HostMetrics) {
        return mergeFrom((com.google.cloud.example.protobuf.HostMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.example.protobuf.HostMetrics other) {
      if (other == com.google.cloud.example.protobuf.HostMetrics.getDefaultInstance()) return this;
      if (other.hasDisk()) {
        mergeDisk(other.getDisk());
      }
      if (other.hasDiskio()) {
        mergeDiskio(other.getDiskio());
      }
      if (other.hasSystemMetrics()) {
        mergeSystemMetrics(other.getSystemMetrics());
      }
      if (other.hasCpuMetrics()) {
        mergeCpuMetrics(other.getCpuMetrics());
      }
      if (netBuilder_ == null) {
        if (!other.net_.isEmpty()) {
          if (net_.isEmpty()) {
            net_ = other.net_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureNetIsMutable();
            net_.addAll(other.net_);
          }
          onChanged();
        }
      } else {
        if (!other.net_.isEmpty()) {
          if (netBuilder_.isEmpty()) {
            netBuilder_.dispose();
            netBuilder_ = null;
            net_ = other.net_;
            bitField0_ = (bitField0_ & ~0x00000010);
            netBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNetFieldBuilder() : null;
          } else {
            netBuilder_.addAllMessages(other.net_);
          }
        }
      }
      if (net2Builder_ == null) {
        if (!other.net2_.isEmpty()) {
          if (net2_.isEmpty()) {
            net2_ = other.net2_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureNet2IsMutable();
            net2_.addAll(other.net2_);
          }
          onChanged();
        }
      } else {
        if (!other.net2_.isEmpty()) {
          if (net2Builder_.isEmpty()) {
            net2Builder_.dispose();
            net2Builder_ = null;
            net2_ = other.net2_;
            bitField0_ = (bitField0_ & ~0x00000020);
            net2Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNet2FieldBuilder() : null;
          } else {
            net2Builder_.addAllMessages(other.net2_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.example.protobuf.HostMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.example.protobuf.HostMetrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.cloud.example.protobuf.DiskMetrics disk_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.DiskMetrics, com.google.cloud.example.protobuf.DiskMetrics.Builder, com.google.cloud.example.protobuf.DiskMetricsOrBuilder> diskBuilder_;
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public boolean hasDisk() {
      return diskBuilder_ != null || disk_ != null;
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public com.google.cloud.example.protobuf.DiskMetrics getDisk() {
      if (diskBuilder_ == null) {
        return disk_ == null ? com.google.cloud.example.protobuf.DiskMetrics.getDefaultInstance() : disk_;
      } else {
        return diskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public Builder setDisk(com.google.cloud.example.protobuf.DiskMetrics value) {
      if (diskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        disk_ = value;
        onChanged();
      } else {
        diskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public Builder setDisk(
        com.google.cloud.example.protobuf.DiskMetrics.Builder builderForValue) {
      if (diskBuilder_ == null) {
        disk_ = builderForValue.build();
        onChanged();
      } else {
        diskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public Builder mergeDisk(com.google.cloud.example.protobuf.DiskMetrics value) {
      if (diskBuilder_ == null) {
        if (disk_ != null) {
          disk_ =
            com.google.cloud.example.protobuf.DiskMetrics.newBuilder(disk_).mergeFrom(value).buildPartial();
        } else {
          disk_ = value;
        }
        onChanged();
      } else {
        diskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public Builder clearDisk() {
      if (diskBuilder_ == null) {
        disk_ = null;
        onChanged();
      } else {
        disk_ = null;
        diskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public com.google.cloud.example.protobuf.DiskMetrics.Builder getDiskBuilder() {
      
      onChanged();
      return getDiskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    public com.google.cloud.example.protobuf.DiskMetricsOrBuilder getDiskOrBuilder() {
      if (diskBuilder_ != null) {
        return diskBuilder_.getMessageOrBuilder();
      } else {
        return disk_ == null ?
            com.google.cloud.example.protobuf.DiskMetrics.getDefaultInstance() : disk_;
      }
    }
    /**
     * <code>.google.protobuf.example.DiskMetrics disk = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.DiskMetrics, com.google.cloud.example.protobuf.DiskMetrics.Builder, com.google.cloud.example.protobuf.DiskMetricsOrBuilder> 
        getDiskFieldBuilder() {
      if (diskBuilder_ == null) {
        diskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.DiskMetrics, com.google.cloud.example.protobuf.DiskMetrics.Builder, com.google.cloud.example.protobuf.DiskMetricsOrBuilder>(
                getDisk(),
                getParentForChildren(),
                isClean());
        disk_ = null;
      }
      return diskBuilder_;
    }

    private com.google.cloud.example.protobuf.DiskIOMetrics diskio_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.DiskIOMetrics, com.google.cloud.example.protobuf.DiskIOMetrics.Builder, com.google.cloud.example.protobuf.DiskIOMetricsOrBuilder> diskioBuilder_;
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public boolean hasDiskio() {
      return diskioBuilder_ != null || diskio_ != null;
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public com.google.cloud.example.protobuf.DiskIOMetrics getDiskio() {
      if (diskioBuilder_ == null) {
        return diskio_ == null ? com.google.cloud.example.protobuf.DiskIOMetrics.getDefaultInstance() : diskio_;
      } else {
        return diskioBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public Builder setDiskio(com.google.cloud.example.protobuf.DiskIOMetrics value) {
      if (diskioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        diskio_ = value;
        onChanged();
      } else {
        diskioBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public Builder setDiskio(
        com.google.cloud.example.protobuf.DiskIOMetrics.Builder builderForValue) {
      if (diskioBuilder_ == null) {
        diskio_ = builderForValue.build();
        onChanged();
      } else {
        diskioBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public Builder mergeDiskio(com.google.cloud.example.protobuf.DiskIOMetrics value) {
      if (diskioBuilder_ == null) {
        if (diskio_ != null) {
          diskio_ =
            com.google.cloud.example.protobuf.DiskIOMetrics.newBuilder(diskio_).mergeFrom(value).buildPartial();
        } else {
          diskio_ = value;
        }
        onChanged();
      } else {
        diskioBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public Builder clearDiskio() {
      if (diskioBuilder_ == null) {
        diskio_ = null;
        onChanged();
      } else {
        diskio_ = null;
        diskioBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public com.google.cloud.example.protobuf.DiskIOMetrics.Builder getDiskioBuilder() {
      
      onChanged();
      return getDiskioFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    public com.google.cloud.example.protobuf.DiskIOMetricsOrBuilder getDiskioOrBuilder() {
      if (diskioBuilder_ != null) {
        return diskioBuilder_.getMessageOrBuilder();
      } else {
        return diskio_ == null ?
            com.google.cloud.example.protobuf.DiskIOMetrics.getDefaultInstance() : diskio_;
      }
    }
    /**
     * <code>.google.protobuf.example.DiskIOMetrics diskio = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.DiskIOMetrics, com.google.cloud.example.protobuf.DiskIOMetrics.Builder, com.google.cloud.example.protobuf.DiskIOMetricsOrBuilder> 
        getDiskioFieldBuilder() {
      if (diskioBuilder_ == null) {
        diskioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.DiskIOMetrics, com.google.cloud.example.protobuf.DiskIOMetrics.Builder, com.google.cloud.example.protobuf.DiskIOMetricsOrBuilder>(
                getDiskio(),
                getParentForChildren(),
                isClean());
        diskio_ = null;
      }
      return diskioBuilder_;
    }

    private com.google.cloud.example.protobuf.SystemMetrics systemMetrics_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.SystemMetrics, com.google.cloud.example.protobuf.SystemMetrics.Builder, com.google.cloud.example.protobuf.SystemMetricsOrBuilder> systemMetricsBuilder_;
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public boolean hasSystemMetrics() {
      return systemMetricsBuilder_ != null || systemMetrics_ != null;
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public com.google.cloud.example.protobuf.SystemMetrics getSystemMetrics() {
      if (systemMetricsBuilder_ == null) {
        return systemMetrics_ == null ? com.google.cloud.example.protobuf.SystemMetrics.getDefaultInstance() : systemMetrics_;
      } else {
        return systemMetricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public Builder setSystemMetrics(com.google.cloud.example.protobuf.SystemMetrics value) {
      if (systemMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        systemMetrics_ = value;
        onChanged();
      } else {
        systemMetricsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public Builder setSystemMetrics(
        com.google.cloud.example.protobuf.SystemMetrics.Builder builderForValue) {
      if (systemMetricsBuilder_ == null) {
        systemMetrics_ = builderForValue.build();
        onChanged();
      } else {
        systemMetricsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public Builder mergeSystemMetrics(com.google.cloud.example.protobuf.SystemMetrics value) {
      if (systemMetricsBuilder_ == null) {
        if (systemMetrics_ != null) {
          systemMetrics_ =
            com.google.cloud.example.protobuf.SystemMetrics.newBuilder(systemMetrics_).mergeFrom(value).buildPartial();
        } else {
          systemMetrics_ = value;
        }
        onChanged();
      } else {
        systemMetricsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public Builder clearSystemMetrics() {
      if (systemMetricsBuilder_ == null) {
        systemMetrics_ = null;
        onChanged();
      } else {
        systemMetrics_ = null;
        systemMetricsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public com.google.cloud.example.protobuf.SystemMetrics.Builder getSystemMetricsBuilder() {
      
      onChanged();
      return getSystemMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    public com.google.cloud.example.protobuf.SystemMetricsOrBuilder getSystemMetricsOrBuilder() {
      if (systemMetricsBuilder_ != null) {
        return systemMetricsBuilder_.getMessageOrBuilder();
      } else {
        return systemMetrics_ == null ?
            com.google.cloud.example.protobuf.SystemMetrics.getDefaultInstance() : systemMetrics_;
      }
    }
    /**
     * <code>.google.protobuf.example.SystemMetrics system_metrics = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.SystemMetrics, com.google.cloud.example.protobuf.SystemMetrics.Builder, com.google.cloud.example.protobuf.SystemMetricsOrBuilder> 
        getSystemMetricsFieldBuilder() {
      if (systemMetricsBuilder_ == null) {
        systemMetricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.SystemMetrics, com.google.cloud.example.protobuf.SystemMetrics.Builder, com.google.cloud.example.protobuf.SystemMetricsOrBuilder>(
                getSystemMetrics(),
                getParentForChildren(),
                isClean());
        systemMetrics_ = null;
      }
      return systemMetricsBuilder_;
    }

    private com.google.cloud.example.protobuf.CPUMetrics cpuMetrics_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.CPUMetrics, com.google.cloud.example.protobuf.CPUMetrics.Builder, com.google.cloud.example.protobuf.CPUMetricsOrBuilder> cpuMetricsBuilder_;
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public boolean hasCpuMetrics() {
      return cpuMetricsBuilder_ != null || cpuMetrics_ != null;
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public com.google.cloud.example.protobuf.CPUMetrics getCpuMetrics() {
      if (cpuMetricsBuilder_ == null) {
        return cpuMetrics_ == null ? com.google.cloud.example.protobuf.CPUMetrics.getDefaultInstance() : cpuMetrics_;
      } else {
        return cpuMetricsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public Builder setCpuMetrics(com.google.cloud.example.protobuf.CPUMetrics value) {
      if (cpuMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cpuMetrics_ = value;
        onChanged();
      } else {
        cpuMetricsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public Builder setCpuMetrics(
        com.google.cloud.example.protobuf.CPUMetrics.Builder builderForValue) {
      if (cpuMetricsBuilder_ == null) {
        cpuMetrics_ = builderForValue.build();
        onChanged();
      } else {
        cpuMetricsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public Builder mergeCpuMetrics(com.google.cloud.example.protobuf.CPUMetrics value) {
      if (cpuMetricsBuilder_ == null) {
        if (cpuMetrics_ != null) {
          cpuMetrics_ =
            com.google.cloud.example.protobuf.CPUMetrics.newBuilder(cpuMetrics_).mergeFrom(value).buildPartial();
        } else {
          cpuMetrics_ = value;
        }
        onChanged();
      } else {
        cpuMetricsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public Builder clearCpuMetrics() {
      if (cpuMetricsBuilder_ == null) {
        cpuMetrics_ = null;
        onChanged();
      } else {
        cpuMetrics_ = null;
        cpuMetricsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public com.google.cloud.example.protobuf.CPUMetrics.Builder getCpuMetricsBuilder() {
      
      onChanged();
      return getCpuMetricsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    public com.google.cloud.example.protobuf.CPUMetricsOrBuilder getCpuMetricsOrBuilder() {
      if (cpuMetricsBuilder_ != null) {
        return cpuMetricsBuilder_.getMessageOrBuilder();
      } else {
        return cpuMetrics_ == null ?
            com.google.cloud.example.protobuf.CPUMetrics.getDefaultInstance() : cpuMetrics_;
      }
    }
    /**
     * <code>.google.protobuf.example.CPUMetrics cpu_metrics = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.CPUMetrics, com.google.cloud.example.protobuf.CPUMetrics.Builder, com.google.cloud.example.protobuf.CPUMetricsOrBuilder> 
        getCpuMetricsFieldBuilder() {
      if (cpuMetricsBuilder_ == null) {
        cpuMetricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.CPUMetrics, com.google.cloud.example.protobuf.CPUMetrics.Builder, com.google.cloud.example.protobuf.CPUMetricsOrBuilder>(
                getCpuMetrics(),
                getParentForChildren(),
                isClean());
        cpuMetrics_ = null;
      }
      return cpuMetricsBuilder_;
    }

    private java.util.List<com.google.cloud.example.protobuf.NetMetrics> net_ =
      java.util.Collections.emptyList();
    private void ensureNetIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        net_ = new java.util.ArrayList<com.google.cloud.example.protobuf.NetMetrics>(net_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.NetMetrics, com.google.cloud.example.protobuf.NetMetrics.Builder, com.google.cloud.example.protobuf.NetMetricsOrBuilder> netBuilder_;

    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.NetMetrics> getNetList() {
      if (netBuilder_ == null) {
        return java.util.Collections.unmodifiableList(net_);
      } else {
        return netBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public int getNetCount() {
      if (netBuilder_ == null) {
        return net_.size();
      } else {
        return netBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics getNet(int index) {
      if (netBuilder_ == null) {
        return net_.get(index);
      } else {
        return netBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder setNet(
        int index, com.google.cloud.example.protobuf.NetMetrics value) {
      if (netBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNetIsMutable();
        net_.set(index, value);
        onChanged();
      } else {
        netBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder setNet(
        int index, com.google.cloud.example.protobuf.NetMetrics.Builder builderForValue) {
      if (netBuilder_ == null) {
        ensureNetIsMutable();
        net_.set(index, builderForValue.build());
        onChanged();
      } else {
        netBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder addNet(com.google.cloud.example.protobuf.NetMetrics value) {
      if (netBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNetIsMutable();
        net_.add(value);
        onChanged();
      } else {
        netBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder addNet(
        int index, com.google.cloud.example.protobuf.NetMetrics value) {
      if (netBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNetIsMutable();
        net_.add(index, value);
        onChanged();
      } else {
        netBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder addNet(
        com.google.cloud.example.protobuf.NetMetrics.Builder builderForValue) {
      if (netBuilder_ == null) {
        ensureNetIsMutable();
        net_.add(builderForValue.build());
        onChanged();
      } else {
        netBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder addNet(
        int index, com.google.cloud.example.protobuf.NetMetrics.Builder builderForValue) {
      if (netBuilder_ == null) {
        ensureNetIsMutable();
        net_.add(index, builderForValue.build());
        onChanged();
      } else {
        netBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder addAllNet(
        java.lang.Iterable<? extends com.google.cloud.example.protobuf.NetMetrics> values) {
      if (netBuilder_ == null) {
        ensureNetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, net_);
        onChanged();
      } else {
        netBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder clearNet() {
      if (netBuilder_ == null) {
        net_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        netBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public Builder removeNet(int index) {
      if (netBuilder_ == null) {
        ensureNetIsMutable();
        net_.remove(index);
        onChanged();
      } else {
        netBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics.Builder getNetBuilder(
        int index) {
      return getNetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public com.google.cloud.example.protobuf.NetMetricsOrBuilder getNetOrBuilder(
        int index) {
      if (netBuilder_ == null) {
        return net_.get(index);  } else {
        return netBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public java.util.List<? extends com.google.cloud.example.protobuf.NetMetricsOrBuilder> 
         getNetOrBuilderList() {
      if (netBuilder_ != null) {
        return netBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(net_);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics.Builder addNetBuilder() {
      return getNetFieldBuilder().addBuilder(
          com.google.cloud.example.protobuf.NetMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics.Builder addNetBuilder(
        int index) {
      return getNetFieldBuilder().addBuilder(
          index, com.google.cloud.example.protobuf.NetMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics net = 5;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.NetMetrics.Builder> 
         getNetBuilderList() {
      return getNetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.NetMetrics, com.google.cloud.example.protobuf.NetMetrics.Builder, com.google.cloud.example.protobuf.NetMetricsOrBuilder> 
        getNetFieldBuilder() {
      if (netBuilder_ == null) {
        netBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.example.protobuf.NetMetrics, com.google.cloud.example.protobuf.NetMetrics.Builder, com.google.cloud.example.protobuf.NetMetricsOrBuilder>(
                net_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        net_ = null;
      }
      return netBuilder_;
    }

    private java.util.List<com.google.cloud.example.protobuf.NetMetrics2> net2_ =
      java.util.Collections.emptyList();
    private void ensureNet2IsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        net2_ = new java.util.ArrayList<com.google.cloud.example.protobuf.NetMetrics2>(net2_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.NetMetrics2, com.google.cloud.example.protobuf.NetMetrics2.Builder, com.google.cloud.example.protobuf.NetMetrics2OrBuilder> net2Builder_;

    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.NetMetrics2> getNet2List() {
      if (net2Builder_ == null) {
        return java.util.Collections.unmodifiableList(net2_);
      } else {
        return net2Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public int getNet2Count() {
      if (net2Builder_ == null) {
        return net2_.size();
      } else {
        return net2Builder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics2 getNet2(int index) {
      if (net2Builder_ == null) {
        return net2_.get(index);
      } else {
        return net2Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder setNet2(
        int index, com.google.cloud.example.protobuf.NetMetrics2 value) {
      if (net2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNet2IsMutable();
        net2_.set(index, value);
        onChanged();
      } else {
        net2Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder setNet2(
        int index, com.google.cloud.example.protobuf.NetMetrics2.Builder builderForValue) {
      if (net2Builder_ == null) {
        ensureNet2IsMutable();
        net2_.set(index, builderForValue.build());
        onChanged();
      } else {
        net2Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder addNet2(com.google.cloud.example.protobuf.NetMetrics2 value) {
      if (net2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNet2IsMutable();
        net2_.add(value);
        onChanged();
      } else {
        net2Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder addNet2(
        int index, com.google.cloud.example.protobuf.NetMetrics2 value) {
      if (net2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNet2IsMutable();
        net2_.add(index, value);
        onChanged();
      } else {
        net2Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder addNet2(
        com.google.cloud.example.protobuf.NetMetrics2.Builder builderForValue) {
      if (net2Builder_ == null) {
        ensureNet2IsMutable();
        net2_.add(builderForValue.build());
        onChanged();
      } else {
        net2Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder addNet2(
        int index, com.google.cloud.example.protobuf.NetMetrics2.Builder builderForValue) {
      if (net2Builder_ == null) {
        ensureNet2IsMutable();
        net2_.add(index, builderForValue.build());
        onChanged();
      } else {
        net2Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder addAllNet2(
        java.lang.Iterable<? extends com.google.cloud.example.protobuf.NetMetrics2> values) {
      if (net2Builder_ == null) {
        ensureNet2IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, net2_);
        onChanged();
      } else {
        net2Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder clearNet2() {
      if (net2Builder_ == null) {
        net2_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        net2Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public Builder removeNet2(int index) {
      if (net2Builder_ == null) {
        ensureNet2IsMutable();
        net2_.remove(index);
        onChanged();
      } else {
        net2Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics2.Builder getNet2Builder(
        int index) {
      return getNet2FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics2OrBuilder getNet2OrBuilder(
        int index) {
      if (net2Builder_ == null) {
        return net2_.get(index);  } else {
        return net2Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public java.util.List<? extends com.google.cloud.example.protobuf.NetMetrics2OrBuilder> 
         getNet2OrBuilderList() {
      if (net2Builder_ != null) {
        return net2Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(net2_);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics2.Builder addNet2Builder() {
      return getNet2FieldBuilder().addBuilder(
          com.google.cloud.example.protobuf.NetMetrics2.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public com.google.cloud.example.protobuf.NetMetrics2.Builder addNet2Builder(
        int index) {
      return getNet2FieldBuilder().addBuilder(
          index, com.google.cloud.example.protobuf.NetMetrics2.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.NetMetrics2 net2 = 6;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.NetMetrics2.Builder> 
         getNet2BuilderList() {
      return getNet2FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.NetMetrics2, com.google.cloud.example.protobuf.NetMetrics2.Builder, com.google.cloud.example.protobuf.NetMetrics2OrBuilder> 
        getNet2FieldBuilder() {
      if (net2Builder_ == null) {
        net2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.example.protobuf.NetMetrics2, com.google.cloud.example.protobuf.NetMetrics2.Builder, com.google.cloud.example.protobuf.NetMetrics2OrBuilder>(
                net2_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        net2_ = null;
      }
      return net2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.example.HostMetrics)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.example.HostMetrics)
  private static final com.google.cloud.example.protobuf.HostMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.example.protobuf.HostMetrics();
  }

  public static com.google.cloud.example.protobuf.HostMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HostMetrics>
      PARSER = new com.google.protobuf.AbstractParser<HostMetrics>() {
    @java.lang.Override
    public HostMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HostMetrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HostMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HostMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.example.protobuf.HostMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

