// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_Metrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_Metrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_HostInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_HostInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_HostMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_HostMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_DiskMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_DiskMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_DiskIOMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_DiskIOMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_NetMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_NetMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_NetMetrics2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_NetMetrics2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_SystemMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_SystemMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_CPUMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_CPUMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_VMMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_VMMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_VMCPUMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_VMCPUMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_VMDiskMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_VMDiskMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_VMMemMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_VMMemMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_example_VMNetMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_example_VMNetMetrics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/instancemetric.proto\022\027google.pro" +
      "tobuf.example\"\266\001\n\007Metrics\022\021\n\ttimestamp\030\001" +
      " \001(\003\0224\n\thost_info\030\002 \001(\0132!.google.protobu" +
      "f.example.HostInfo\0222\n\004host\030\003 \001(\0132$.googl" +
      "e.protobuf.example.HostMetrics\022.\n\002vm\030\004 \003" +
      "(\0132\".google.protobuf.example.VMMetrics\"t" +
      "\n\010HostInfo\022\014\n\004rack\030\001 \001(\t\022\024\n\014cloud_region" +
      "\030\002 \001(\t\022\014\n\004host\030\003 \001(\t\022\020\n\010nodetype\030\004 \001(\t\022\n" +
      "\n\002ip\030\005 \001(\t\022\n\n\002dc\030\006 \001(\t\022\014\n\004mdom\030\007 \001(\t\"\331\002\n" +
      "\013HostMetrics\0222\n\004disk\030\001 \001(\0132$.google.prot" +
      "obuf.example.DiskMetrics\0226\n\006diskio\030\002 \001(\013" +
      "2&.google.protobuf.example.DiskIOMetrics" +
      "\022>\n\016system_metrics\030\003 \001(\0132&.google.protob" +
      "uf.example.SystemMetrics\0228\n\013cpu_metrics\030" +
      "\004 \001(\0132#.google.protobuf.example.CPUMetri" +
      "cs\0220\n\003net\030\005 \003(\0132#.google.protobuf.exampl" +
      "e.NetMetrics\0222\n\004net2\030\006 \003(\0132$.google.prot" +
      "obuf.example.NetMetrics2\"\312\001\n\013DiskMetrics" +
      "\022\014\n\004mode\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\022\016\n\006device\030\003" +
      " \001(\t\022\016\n\006fstype\030\004 \001(\t\022\023\n\013inodes_free\030\005 \001(" +
      "\003\022\023\n\013inodes_used\030\006 \001(\003\022\r\n\005total\030\007 \001(\003\022\014\n" +
      "\004free\030\010 \001(\003\022\014\n\004used\030\t \001(\003\022\024\n\014used_percen" +
      "t\030\n \001(\002\022\024\n\014inodes_total\030\013 \001(\003\"\321\001\n\rDiskIO" +
      "Metrics\022\014\n\004name\030\001 \001(\t\022\r\n\005reads\030\002 \001(\003\022\016\n\006" +
      "writes\030\003 \001(\003\022\023\n\013write_bytes\030\004 \001(\003\022\021\n\trea" +
      "d_time\030\005 \001(\003\022\030\n\020weighted_io_time\030\006 \001(\003\022\022" +
      "\n\nread_bytes\030\007 \001(\003\022\022\n\nwrite_time\030\010 \001(\003\022\017" +
      "\n\007io_time\030\t \001(\003\022\030\n\020iops_in_progress\030\n \001(" +
      "\003\"\267\001\n\nNetMetrics\022\021\n\tinterface\030\001 \001(\t\022\017\n\007e" +
      "rr_out\030\002 \001(\003\022\022\n\nbytes_sent\030\003 \001(\003\022\024\n\014pack" +
      "ets_sent\030\004 \001(\003\022\024\n\014packets_recv\030\005 \001(\003\022\020\n\010" +
      "drop_out\030\006 \001(\003\022\022\n\nbytes_recv\030\007 \001(\003\022\016\n\006er" +
      "r_in\030\010 \001(\003\022\017\n\007drop_in\030\t \001(\003\"\224\020\n\013NetMetri" +
      "cs2\022\021\n\tinterface\030\001 \001(\t\022\030\n\020udp_rcvbuferro" +
      "rs\030\002 \001(\005\022\025\n\rip_indiscards\030\003 \001(\005\022\035\n\025icmp_" +
      "outtimestampreps\030\004 \001(\005\022\025\n\ricmp_outechos\030" +
      "\005 \001(\005\022\030\n\020udp_ignoredmulti\030\006 \001(\003\022\034\n\024udpli" +
      "te_outdatagrams\030\007 \001(\005\022\027\n\017ip_reasmtimeout" +
      "\030\010 \001(\005\022\022\n\nip_fragoks\030\t \001(\005\022\023\n\013icmp_inmsg" +
      "s\030\n \001(\005\022\030\n\020udp_incsumerrors\030\013 \001(\005\022\025\n\rip_" +
      "reasmreqds\030\014 \001(\005\022\031\n\021icmp_outaddrmasks\030\r " +
      "\001(\005\022\022\n\ntcp_rtomax\030\016 \001(\003\022\034\n\024udplite_rcvbu" +
      "ferrors\030\017 \001(\005\022\025\n\rip_reasmfails\030\020 \001(\005\022\023\n\013" +
      "tcp_maxconn\030\021 \001(\005\022\022\n\ntcp_rtomin\030\022 \001(\005\022\030\n" +
      "\020tcp_passiveopens\030\023 \001(\003\022\026\n\016ip_fragcreate" +
      "s\030\024 \001(\005\022\031\n\021icmp_incsumerrors\030\025 \001(\005\022\033\n\023ud" +
      "plite_indatagrams\030\026 \001(\005\022\023\n\013ip_reasmoks\030\027" +
      " \001(\005\022\030\n\020icmp_intimeexcds\030\030 \001(\005\022\031\n\021icmp_o" +
      "uttimeexcds\030\031 \001(\005\022\022\n\ntcp_inerrs\030\032 \001(\005\022\034\n" +
      "\024icmp_outaddrmaskreps\030\033 \001(\005\022\027\n\017icmpmsg_o" +
      "uttype\030\034 \001(\005\022\023\n\013udp_noports\030\035 \001(\005\022\027\n\017icm" +
      "pmsg_intype8\030\036 \001(\005\022\022\n\ntcp_insegs\030\037 \001(\003\022\027" +
      "\n\017udplite_noports\030  \001(\005\022\024\n\014ip_fragfails\030" +
      "! \001(\005\022\025\n\rip_indelivers\030\" \001(\003\022\032\n\022icmp_out" +
      "timestamps\030# \001(\005\022\030\n\020icmp_outechoreps\030$ \001" +
      "(\005\022\030\n\020tcp_incsumerrors\030% \001(\005\022\030\n\020tcp_rtoa" +
      "lgorithm\030& \001(\005\022\030\n\020ip_forwdatagrams\030\' \001(\005" +
      "\022\031\n\021icmp_insrcquenchs\030( \001(\005\022\034\n\024icmp_outd" +
      "estunreachs\030) \001(\005\022\031\n\021icmp_outparmprobs\030*" +
      " \001(\005\022\026\n\016ip_outnoroutes\030+ \001(\005\022\027\n\017icmp_ine" +
      "choreps\030, \001(\005\022\030\n\020udplite_inerrors\030- \001(\005\022" +
      "\025\n\rtcp_currestab\030. \001(\005\022\032\n\022ip_inunknownpr" +
      "otos\030/ \001(\005\022\024\n\014icmp_inechos\0300 \001(\005\022\030\n\020icmp" +
      "_inparmprobs\0301 \001(\005\022\025\n\ricmp_inerrors\0302 \001(" +
      "\005\022\027\n\017tcp_activeopens\0303 \001(\005\022\023\n\013tcp_outrst" +
      "s\0304 \001(\005\022\034\n\024udplite_ignoredmulti\0305 \001(\005\022\025\n" +
      "\rip_forwarding\0306 \001(\005\022\025\n\rip_inreceives\0307 " +
      "\001(\003\022\026\n\016ip_outdiscards\0308 \001(\005\022\030\n\020icmp_inre" +
      "directs\0309 \001(\005\022\033\n\023icmp_inaddrmaskreps\030: \001" +
      "(\005\022\030\n\020icmp_inaddrmasks\030; \001(\005\022\026\n\016icmp_out" +
      "errors\030< \001(\005\022\023\n\013tcp_outsegs\030= \001(\003\022\025\n\rip_" +
      "defaultttl\030> \001(\005\022\027\n\017ip_inaddrerrors\030? \001(" +
      "\005\022\032\n\022icmp_outsrcquenchs\030@ \001(\005\022\031\n\021icmp_ou" +
      "tredirects\030A \001(\005\022\027\n\017tcp_estabresets\030B \001(" +
      "\003\022\034\n\024udplite_sndbuferrors\030C \001(\005\022\026\n\016ip_ou" +
      "trequests\030D \001(\003\022\024\n\014icmp_outmsgs\030E \001(\005\022\027\n" +
      "\017tcp_retranssegs\030F \001(\003\022\030\n\020udp_outdatagra" +
      "ms\030G \001(\003\022\030\n\020udp_sndbuferrors\030H \001(\005\022\031\n\021ic" +
      "mp_intimestamps\030I \001(\005\022\033\n\023icmp_indestunre" +
      "achs\030J \001(\005\022\030\n\020icmpmsg_outtype0\030K \001(\005\022\027\n\017" +
      "udp_indatagrams\030L \001(\005\022\024\n\014udp_inerrors\030M " +
      "\001(\005\022\034\n\024udplite_incsumerrors\030N \001(\005\022\026\n\016ip_" +
      "inhdrerrors\030O \001(\005\022\034\n\024icmp_intimestamprep" +
      "s\030P \001(\005\022\027\n\017icmpmsg_intype3\030Q \001(\005\022\030\n\020tcp_" +
      "attemptfails\030R \001(\005\"u\n\rSystemMetrics\022\r\n\005l" +
      "oad1\030\001 \001(\002\022\r\n\005load5\030\002 \001(\002\022\016\n\006load15\030\003 \001(" +
      "\002\022\017\n\007n_users\030\004 \001(\005\022\016\n\006n_cpus\030\005 \001(\005\022\025\n\rup" +
      "time_format\030\006 \001(\t\"\357\001\n\nCPUMetrics\022\013\n\003cpu\030" +
      "\001 \001(\t\022\022\n\nusage_user\030\002 \001(\002\022\024\n\014usage_syste" +
      "m\030\003 \001(\002\022\022\n\nusage_idle\030\004 \001(\002\022\021\n\tusage_irq" +
      "\030\005 \001(\005\022\025\n\rusage_softirq\030\006 \001(\002\022\023\n\013usage_s" +
      "teal\030\007 \001(\005\022\022\n\nusage_nice\030\010 \001(\005\022\024\n\014usage_" +
      "iowait\030\t \001(\005\022\023\n\013usage_guest\030\n \001(\002\022\030\n\020usa" +
      "ge_guest_nice\030\013 \001(\005\"\367\001\n\tVMMetrics\022\014\n\004vmi" +
      "d\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\0222\n\003cpu\030\003 \001(\0132%.googl" +
      "e.protobuf.example.VMCPUMetrics\0224\n\004disk\030" +
      "\004 \001(\0132&.google.protobuf.example.VMDiskMe" +
      "trics\0222\n\003mem\030\005 \001(\0132%.google.protobuf.exa" +
      "mple.VMMemMetrics\0222\n\003net\030\006 \001(\0132%.google." +
      "protobuf.example.VMNetMetrics\"\241\001\n\014VMCPUM" +
      "etrics\022 \n\030cpu_data_cputime_percent\030\001 \001(\002" +
      "\022\031\n\021aggregate_cputime\030\002 \001(\003\022\035\n\025aggregate" +
      "_system_time\030\003 \001(\003\022\033\n\023aggregate_user_tim" +
      "e\030\004 \001(\003\022\030\n\020cpu_data_cputime\030\005 \001(\003\"\200\001\n\rVM" +
      "DiskMetrics\022\021\n\tdisk_name\030\001 \001(\t\022\021\n\twrite_" +
      "req\030\002 \001(\003\022\022\n\nread_bytes\030\003 \001(\003\022\016\n\006errors\030" +
      "\004 \001(\003\022\020\n\010read_req\030\005 \001(\003\022\023\n\013write_bytes\030\006" +
      " \001(\003\"N\n\014VMMemMetrics\022\024\n\014total_memory\030\001 \001" +
      "(\003\022\023\n\013free_memory\030\002 \001(\003\022\023\n\013memory_util\030\003" +
      " \001(\002\"\266\001\n\014VMNetMetrics\022\026\n\016interface_name\030" +
      "\001 \001(\t\022\017\n\007rx_drop\030\002 \001(\003\022\022\n\nrx_packets\030\003 \001" +
      "(\003\022\017\n\007tx_errs\030\004 \001(\003\022\017\n\007rx_errs\030\005 \001(\003\022\020\n\010" +
      "rx_bytes\030\006 \001(\003\022\017\n\007tx_drop\030\007 \001(\003\022\020\n\010tx_by" +
      "tes\030\010 \001(\003\022\022\n\ntx_packets\030\t \001(\003B3\n!com.goo" +
      "gle.cloud.example.protobufB\014MetricsProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_example_Metrics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_example_Metrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_Metrics_descriptor,
        new java.lang.String[] { "Timestamp", "HostInfo", "Host", "Vm", });
    internal_static_google_protobuf_example_HostInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_example_HostInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_HostInfo_descriptor,
        new java.lang.String[] { "Rack", "CloudRegion", "Host", "Nodetype", "Ip", "Dc", "Mdom", });
    internal_static_google_protobuf_example_HostMetrics_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_example_HostMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_HostMetrics_descriptor,
        new java.lang.String[] { "Disk", "Diskio", "SystemMetrics", "CpuMetrics", "Net", "Net2", });
    internal_static_google_protobuf_example_DiskMetrics_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_protobuf_example_DiskMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_DiskMetrics_descriptor,
        new java.lang.String[] { "Mode", "Path", "Device", "Fstype", "InodesFree", "InodesUsed", "Total", "Free", "Used", "UsedPercent", "InodesTotal", });
    internal_static_google_protobuf_example_DiskIOMetrics_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_protobuf_example_DiskIOMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_DiskIOMetrics_descriptor,
        new java.lang.String[] { "Name", "Reads", "Writes", "WriteBytes", "ReadTime", "WeightedIoTime", "ReadBytes", "WriteTime", "IoTime", "IopsInProgress", });
    internal_static_google_protobuf_example_NetMetrics_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_protobuf_example_NetMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_NetMetrics_descriptor,
        new java.lang.String[] { "Interface", "ErrOut", "BytesSent", "PacketsSent", "PacketsRecv", "DropOut", "BytesRecv", "ErrIn", "DropIn", });
    internal_static_google_protobuf_example_NetMetrics2_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_protobuf_example_NetMetrics2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_NetMetrics2_descriptor,
        new java.lang.String[] { "Interface", "UdpRcvbuferrors", "IpIndiscards", "IcmpOuttimestampreps", "IcmpOutechos", "UdpIgnoredmulti", "UdpliteOutdatagrams", "IpReasmtimeout", "IpFragoks", "IcmpInmsgs", "UdpIncsumerrors", "IpReasmreqds", "IcmpOutaddrmasks", "TcpRtomax", "UdpliteRcvbuferrors", "IpReasmfails", "TcpMaxconn", "TcpRtomin", "TcpPassiveopens", "IpFragcreates", "IcmpIncsumerrors", "UdpliteIndatagrams", "IpReasmoks", "IcmpIntimeexcds", "IcmpOuttimeexcds", "TcpInerrs", "IcmpOutaddrmaskreps", "IcmpmsgOuttype", "UdpNoports", "IcmpmsgIntype8", "TcpInsegs", "UdpliteNoports", "IpFragfails", "IpIndelivers", "IcmpOuttimestamps", "IcmpOutechoreps", "TcpIncsumerrors", "TcpRtoalgorithm", "IpForwdatagrams", "IcmpInsrcquenchs", "IcmpOutdestunreachs", "IcmpOutparmprobs", "IpOutnoroutes", "IcmpInechoreps", "UdpliteInerrors", "TcpCurrestab", "IpInunknownprotos", "IcmpInechos", "IcmpInparmprobs", "IcmpInerrors", "TcpActiveopens", "TcpOutrsts", "UdpliteIgnoredmulti", "IpForwarding", "IpInreceives", "IpOutdiscards", "IcmpInredirects", "IcmpInaddrmaskreps", "IcmpInaddrmasks", "IcmpOuterrors", "TcpOutsegs", "IpDefaultttl", "IpInaddrerrors", "IcmpOutsrcquenchs", "IcmpOutredirects", "TcpEstabresets", "UdpliteSndbuferrors", "IpOutrequests", "IcmpOutmsgs", "TcpRetranssegs", "UdpOutdatagrams", "UdpSndbuferrors", "IcmpIntimestamps", "IcmpIndestunreachs", "IcmpmsgOuttype0", "UdpIndatagrams", "UdpInerrors", "UdpliteIncsumerrors", "IpInhdrerrors", "IcmpIntimestampreps", "IcmpmsgIntype3", "TcpAttemptfails", });
    internal_static_google_protobuf_example_SystemMetrics_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_protobuf_example_SystemMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_SystemMetrics_descriptor,
        new java.lang.String[] { "Load1", "Load5", "Load15", "NUsers", "NCpus", "UptimeFormat", });
    internal_static_google_protobuf_example_CPUMetrics_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_protobuf_example_CPUMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_CPUMetrics_descriptor,
        new java.lang.String[] { "Cpu", "UsageUser", "UsageSystem", "UsageIdle", "UsageIrq", "UsageSoftirq", "UsageSteal", "UsageNice", "UsageIowait", "UsageGuest", "UsageGuestNice", });
    internal_static_google_protobuf_example_VMMetrics_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_protobuf_example_VMMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_VMMetrics_descriptor,
        new java.lang.String[] { "Vmid", "Ip", "Cpu", "Disk", "Mem", "Net", });
    internal_static_google_protobuf_example_VMCPUMetrics_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_protobuf_example_VMCPUMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_VMCPUMetrics_descriptor,
        new java.lang.String[] { "CpuDataCputimePercent", "AggregateCputime", "AggregateSystemTime", "AggregateUserTime", "CpuDataCputime", });
    internal_static_google_protobuf_example_VMDiskMetrics_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_protobuf_example_VMDiskMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_VMDiskMetrics_descriptor,
        new java.lang.String[] { "DiskName", "WriteReq", "ReadBytes", "Errors", "ReadReq", "WriteBytes", });
    internal_static_google_protobuf_example_VMMemMetrics_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_protobuf_example_VMMemMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_VMMemMetrics_descriptor,
        new java.lang.String[] { "TotalMemory", "FreeMemory", "MemoryUtil", });
    internal_static_google_protobuf_example_VMNetMetrics_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_protobuf_example_VMNetMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_example_VMNetMetrics_descriptor,
        new java.lang.String[] { "InterfaceName", "RxDrop", "RxPackets", "TxErrs", "RxErrs", "RxBytes", "TxDrop", "TxBytes", "TxPackets", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
