// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

/**
 * Protobuf type {@code google.protobuf.example.Metrics}
 */
public  final class Metrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.example.Metrics)
    MetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Metrics.newBuilder() to construct.
  private Metrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Metrics() {
    timestamp_ = 0L;
    vm_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Metrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timestamp_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.cloud.example.protobuf.HostInfo.Builder subBuilder = null;
            if (hostInfo_ != null) {
              subBuilder = hostInfo_.toBuilder();
            }
            hostInfo_ = input.readMessage(com.google.cloud.example.protobuf.HostInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hostInfo_);
              hostInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.cloud.example.protobuf.HostMetrics.Builder subBuilder = null;
            if (host_ != null) {
              subBuilder = host_.toBuilder();
            }
            host_ = input.readMessage(com.google.cloud.example.protobuf.HostMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(host_);
              host_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              vm_ = new java.util.ArrayList<com.google.cloud.example.protobuf.VMMetrics>();
              mutable_bitField0_ |= 0x00000008;
            }
            vm_.add(
                input.readMessage(com.google.cloud.example.protobuf.VMMetrics.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        vm_ = java.util.Collections.unmodifiableList(vm_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_Metrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_Metrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.example.protobuf.Metrics.class, com.google.cloud.example.protobuf.Metrics.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 1;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int HOST_INFO_FIELD_NUMBER = 2;
  private com.google.cloud.example.protobuf.HostInfo hostInfo_;
  /**
   * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
   */
  public boolean hasHostInfo() {
    return hostInfo_ != null;
  }
  /**
   * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
   */
  public com.google.cloud.example.protobuf.HostInfo getHostInfo() {
    return hostInfo_ == null ? com.google.cloud.example.protobuf.HostInfo.getDefaultInstance() : hostInfo_;
  }
  /**
   * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
   */
  public com.google.cloud.example.protobuf.HostInfoOrBuilder getHostInfoOrBuilder() {
    return getHostInfo();
  }

  public static final int HOST_FIELD_NUMBER = 3;
  private com.google.cloud.example.protobuf.HostMetrics host_;
  /**
   * <code>.google.protobuf.example.HostMetrics host = 3;</code>
   */
  public boolean hasHost() {
    return host_ != null;
  }
  /**
   * <code>.google.protobuf.example.HostMetrics host = 3;</code>
   */
  public com.google.cloud.example.protobuf.HostMetrics getHost() {
    return host_ == null ? com.google.cloud.example.protobuf.HostMetrics.getDefaultInstance() : host_;
  }
  /**
   * <code>.google.protobuf.example.HostMetrics host = 3;</code>
   */
  public com.google.cloud.example.protobuf.HostMetricsOrBuilder getHostOrBuilder() {
    return getHost();
  }

  public static final int VM_FIELD_NUMBER = 4;
  private java.util.List<com.google.cloud.example.protobuf.VMMetrics> vm_;
  /**
   * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
   */
  public java.util.List<com.google.cloud.example.protobuf.VMMetrics> getVmList() {
    return vm_;
  }
  /**
   * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
   */
  public java.util.List<? extends com.google.cloud.example.protobuf.VMMetricsOrBuilder> 
      getVmOrBuilderList() {
    return vm_;
  }
  /**
   * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
   */
  public int getVmCount() {
    return vm_.size();
  }
  /**
   * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
   */
  public com.google.cloud.example.protobuf.VMMetrics getVm(int index) {
    return vm_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
   */
  public com.google.cloud.example.protobuf.VMMetricsOrBuilder getVmOrBuilder(
      int index) {
    return vm_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (hostInfo_ != null) {
      output.writeMessage(2, getHostInfo());
    }
    if (host_ != null) {
      output.writeMessage(3, getHost());
    }
    for (int i = 0; i < vm_.size(); i++) {
      output.writeMessage(4, vm_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (hostInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHostInfo());
    }
    if (host_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getHost());
    }
    for (int i = 0; i < vm_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, vm_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.example.protobuf.Metrics)) {
      return super.equals(obj);
    }
    com.google.cloud.example.protobuf.Metrics other = (com.google.cloud.example.protobuf.Metrics) obj;

    boolean result = true;
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && (hasHostInfo() == other.hasHostInfo());
    if (hasHostInfo()) {
      result = result && getHostInfo()
          .equals(other.getHostInfo());
    }
    result = result && (hasHost() == other.hasHost());
    if (hasHost()) {
      result = result && getHost()
          .equals(other.getHost());
    }
    result = result && getVmList()
        .equals(other.getVmList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasHostInfo()) {
      hash = (37 * hash) + HOST_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getHostInfo().hashCode();
    }
    if (hasHost()) {
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
    }
    if (getVmCount() > 0) {
      hash = (37 * hash) + VM_FIELD_NUMBER;
      hash = (53 * hash) + getVmList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.Metrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.Metrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.Metrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.example.protobuf.Metrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.example.Metrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.example.Metrics)
      com.google.cloud.example.protobuf.MetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_Metrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_Metrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.example.protobuf.Metrics.class, com.google.cloud.example.protobuf.Metrics.Builder.class);
    }

    // Construct using com.google.cloud.example.protobuf.Metrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVmFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      if (hostInfoBuilder_ == null) {
        hostInfo_ = null;
      } else {
        hostInfo_ = null;
        hostInfoBuilder_ = null;
      }
      if (hostBuilder_ == null) {
        host_ = null;
      } else {
        host_ = null;
        hostBuilder_ = null;
      }
      if (vmBuilder_ == null) {
        vm_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        vmBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_Metrics_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.Metrics getDefaultInstanceForType() {
      return com.google.cloud.example.protobuf.Metrics.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.Metrics build() {
      com.google.cloud.example.protobuf.Metrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.Metrics buildPartial() {
      com.google.cloud.example.protobuf.Metrics result = new com.google.cloud.example.protobuf.Metrics(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.timestamp_ = timestamp_;
      if (hostInfoBuilder_ == null) {
        result.hostInfo_ = hostInfo_;
      } else {
        result.hostInfo_ = hostInfoBuilder_.build();
      }
      if (hostBuilder_ == null) {
        result.host_ = host_;
      } else {
        result.host_ = hostBuilder_.build();
      }
      if (vmBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          vm_ = java.util.Collections.unmodifiableList(vm_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.vm_ = vm_;
      } else {
        result.vm_ = vmBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.example.protobuf.Metrics) {
        return mergeFrom((com.google.cloud.example.protobuf.Metrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.example.protobuf.Metrics other) {
      if (other == com.google.cloud.example.protobuf.Metrics.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasHostInfo()) {
        mergeHostInfo(other.getHostInfo());
      }
      if (other.hasHost()) {
        mergeHost(other.getHost());
      }
      if (vmBuilder_ == null) {
        if (!other.vm_.isEmpty()) {
          if (vm_.isEmpty()) {
            vm_ = other.vm_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVmIsMutable();
            vm_.addAll(other.vm_);
          }
          onChanged();
        }
      } else {
        if (!other.vm_.isEmpty()) {
          if (vmBuilder_.isEmpty()) {
            vmBuilder_.dispose();
            vmBuilder_ = null;
            vm_ = other.vm_;
            bitField0_ = (bitField0_ & ~0x00000008);
            vmBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVmFieldBuilder() : null;
          } else {
            vmBuilder_.addAllMessages(other.vm_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.example.protobuf.Metrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.example.protobuf.Metrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.cloud.example.protobuf.HostInfo hostInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.HostInfo, com.google.cloud.example.protobuf.HostInfo.Builder, com.google.cloud.example.protobuf.HostInfoOrBuilder> hostInfoBuilder_;
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public boolean hasHostInfo() {
      return hostInfoBuilder_ != null || hostInfo_ != null;
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public com.google.cloud.example.protobuf.HostInfo getHostInfo() {
      if (hostInfoBuilder_ == null) {
        return hostInfo_ == null ? com.google.cloud.example.protobuf.HostInfo.getDefaultInstance() : hostInfo_;
      } else {
        return hostInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public Builder setHostInfo(com.google.cloud.example.protobuf.HostInfo value) {
      if (hostInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hostInfo_ = value;
        onChanged();
      } else {
        hostInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public Builder setHostInfo(
        com.google.cloud.example.protobuf.HostInfo.Builder builderForValue) {
      if (hostInfoBuilder_ == null) {
        hostInfo_ = builderForValue.build();
        onChanged();
      } else {
        hostInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public Builder mergeHostInfo(com.google.cloud.example.protobuf.HostInfo value) {
      if (hostInfoBuilder_ == null) {
        if (hostInfo_ != null) {
          hostInfo_ =
            com.google.cloud.example.protobuf.HostInfo.newBuilder(hostInfo_).mergeFrom(value).buildPartial();
        } else {
          hostInfo_ = value;
        }
        onChanged();
      } else {
        hostInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public Builder clearHostInfo() {
      if (hostInfoBuilder_ == null) {
        hostInfo_ = null;
        onChanged();
      } else {
        hostInfo_ = null;
        hostInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public com.google.cloud.example.protobuf.HostInfo.Builder getHostInfoBuilder() {
      
      onChanged();
      return getHostInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    public com.google.cloud.example.protobuf.HostInfoOrBuilder getHostInfoOrBuilder() {
      if (hostInfoBuilder_ != null) {
        return hostInfoBuilder_.getMessageOrBuilder();
      } else {
        return hostInfo_ == null ?
            com.google.cloud.example.protobuf.HostInfo.getDefaultInstance() : hostInfo_;
      }
    }
    /**
     * <code>.google.protobuf.example.HostInfo host_info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.HostInfo, com.google.cloud.example.protobuf.HostInfo.Builder, com.google.cloud.example.protobuf.HostInfoOrBuilder> 
        getHostInfoFieldBuilder() {
      if (hostInfoBuilder_ == null) {
        hostInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.HostInfo, com.google.cloud.example.protobuf.HostInfo.Builder, com.google.cloud.example.protobuf.HostInfoOrBuilder>(
                getHostInfo(),
                getParentForChildren(),
                isClean());
        hostInfo_ = null;
      }
      return hostInfoBuilder_;
    }

    private com.google.cloud.example.protobuf.HostMetrics host_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.HostMetrics, com.google.cloud.example.protobuf.HostMetrics.Builder, com.google.cloud.example.protobuf.HostMetricsOrBuilder> hostBuilder_;
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public boolean hasHost() {
      return hostBuilder_ != null || host_ != null;
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public com.google.cloud.example.protobuf.HostMetrics getHost() {
      if (hostBuilder_ == null) {
        return host_ == null ? com.google.cloud.example.protobuf.HostMetrics.getDefaultInstance() : host_;
      } else {
        return hostBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public Builder setHost(com.google.cloud.example.protobuf.HostMetrics value) {
      if (hostBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        host_ = value;
        onChanged();
      } else {
        hostBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public Builder setHost(
        com.google.cloud.example.protobuf.HostMetrics.Builder builderForValue) {
      if (hostBuilder_ == null) {
        host_ = builderForValue.build();
        onChanged();
      } else {
        hostBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public Builder mergeHost(com.google.cloud.example.protobuf.HostMetrics value) {
      if (hostBuilder_ == null) {
        if (host_ != null) {
          host_ =
            com.google.cloud.example.protobuf.HostMetrics.newBuilder(host_).mergeFrom(value).buildPartial();
        } else {
          host_ = value;
        }
        onChanged();
      } else {
        hostBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public Builder clearHost() {
      if (hostBuilder_ == null) {
        host_ = null;
        onChanged();
      } else {
        host_ = null;
        hostBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public com.google.cloud.example.protobuf.HostMetrics.Builder getHostBuilder() {
      
      onChanged();
      return getHostFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    public com.google.cloud.example.protobuf.HostMetricsOrBuilder getHostOrBuilder() {
      if (hostBuilder_ != null) {
        return hostBuilder_.getMessageOrBuilder();
      } else {
        return host_ == null ?
            com.google.cloud.example.protobuf.HostMetrics.getDefaultInstance() : host_;
      }
    }
    /**
     * <code>.google.protobuf.example.HostMetrics host = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.HostMetrics, com.google.cloud.example.protobuf.HostMetrics.Builder, com.google.cloud.example.protobuf.HostMetricsOrBuilder> 
        getHostFieldBuilder() {
      if (hostBuilder_ == null) {
        hostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.HostMetrics, com.google.cloud.example.protobuf.HostMetrics.Builder, com.google.cloud.example.protobuf.HostMetricsOrBuilder>(
                getHost(),
                getParentForChildren(),
                isClean());
        host_ = null;
      }
      return hostBuilder_;
    }

    private java.util.List<com.google.cloud.example.protobuf.VMMetrics> vm_ =
      java.util.Collections.emptyList();
    private void ensureVmIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        vm_ = new java.util.ArrayList<com.google.cloud.example.protobuf.VMMetrics>(vm_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.VMMetrics, com.google.cloud.example.protobuf.VMMetrics.Builder, com.google.cloud.example.protobuf.VMMetricsOrBuilder> vmBuilder_;

    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.VMMetrics> getVmList() {
      if (vmBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vm_);
      } else {
        return vmBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public int getVmCount() {
      if (vmBuilder_ == null) {
        return vm_.size();
      } else {
        return vmBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMMetrics getVm(int index) {
      if (vmBuilder_ == null) {
        return vm_.get(index);
      } else {
        return vmBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder setVm(
        int index, com.google.cloud.example.protobuf.VMMetrics value) {
      if (vmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVmIsMutable();
        vm_.set(index, value);
        onChanged();
      } else {
        vmBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder setVm(
        int index, com.google.cloud.example.protobuf.VMMetrics.Builder builderForValue) {
      if (vmBuilder_ == null) {
        ensureVmIsMutable();
        vm_.set(index, builderForValue.build());
        onChanged();
      } else {
        vmBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder addVm(com.google.cloud.example.protobuf.VMMetrics value) {
      if (vmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVmIsMutable();
        vm_.add(value);
        onChanged();
      } else {
        vmBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder addVm(
        int index, com.google.cloud.example.protobuf.VMMetrics value) {
      if (vmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVmIsMutable();
        vm_.add(index, value);
        onChanged();
      } else {
        vmBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder addVm(
        com.google.cloud.example.protobuf.VMMetrics.Builder builderForValue) {
      if (vmBuilder_ == null) {
        ensureVmIsMutable();
        vm_.add(builderForValue.build());
        onChanged();
      } else {
        vmBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder addVm(
        int index, com.google.cloud.example.protobuf.VMMetrics.Builder builderForValue) {
      if (vmBuilder_ == null) {
        ensureVmIsMutable();
        vm_.add(index, builderForValue.build());
        onChanged();
      } else {
        vmBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder addAllVm(
        java.lang.Iterable<? extends com.google.cloud.example.protobuf.VMMetrics> values) {
      if (vmBuilder_ == null) {
        ensureVmIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vm_);
        onChanged();
      } else {
        vmBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder clearVm() {
      if (vmBuilder_ == null) {
        vm_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        vmBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public Builder removeVm(int index) {
      if (vmBuilder_ == null) {
        ensureVmIsMutable();
        vm_.remove(index);
        onChanged();
      } else {
        vmBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMMetrics.Builder getVmBuilder(
        int index) {
      return getVmFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMMetricsOrBuilder getVmOrBuilder(
        int index) {
      if (vmBuilder_ == null) {
        return vm_.get(index);  } else {
        return vmBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public java.util.List<? extends com.google.cloud.example.protobuf.VMMetricsOrBuilder> 
         getVmOrBuilderList() {
      if (vmBuilder_ != null) {
        return vmBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vm_);
      }
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMMetrics.Builder addVmBuilder() {
      return getVmFieldBuilder().addBuilder(
          com.google.cloud.example.protobuf.VMMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMMetrics.Builder addVmBuilder(
        int index) {
      return getVmFieldBuilder().addBuilder(
          index, com.google.cloud.example.protobuf.VMMetrics.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.example.VMMetrics vm = 4;</code>
     */
    public java.util.List<com.google.cloud.example.protobuf.VMMetrics.Builder> 
         getVmBuilderList() {
      return getVmFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.cloud.example.protobuf.VMMetrics, com.google.cloud.example.protobuf.VMMetrics.Builder, com.google.cloud.example.protobuf.VMMetricsOrBuilder> 
        getVmFieldBuilder() {
      if (vmBuilder_ == null) {
        vmBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.cloud.example.protobuf.VMMetrics, com.google.cloud.example.protobuf.VMMetrics.Builder, com.google.cloud.example.protobuf.VMMetricsOrBuilder>(
                vm_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        vm_ = null;
      }
      return vmBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.example.Metrics)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.example.Metrics)
  private static final com.google.cloud.example.protobuf.Metrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.example.protobuf.Metrics();
  }

  public static com.google.cloud.example.protobuf.Metrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metrics>
      PARSER = new com.google.protobuf.AbstractParser<Metrics>() {
    @java.lang.Override
    public Metrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Metrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Metrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.example.protobuf.Metrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

