// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

/**
 * Protobuf type {@code google.protobuf.example.NetMetrics}
 */
public  final class NetMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.example.NetMetrics)
    NetMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetMetrics.newBuilder() to construct.
  private NetMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetMetrics() {
    interface_ = "";
    errOut_ = 0L;
    bytesSent_ = 0L;
    packetsSent_ = 0L;
    packetsRecv_ = 0L;
    dropOut_ = 0L;
    bytesRecv_ = 0L;
    errIn_ = 0L;
    dropIn_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            interface_ = s;
            break;
          }
          case 16: {

            errOut_ = input.readInt64();
            break;
          }
          case 24: {

            bytesSent_ = input.readInt64();
            break;
          }
          case 32: {

            packetsSent_ = input.readInt64();
            break;
          }
          case 40: {

            packetsRecv_ = input.readInt64();
            break;
          }
          case 48: {

            dropOut_ = input.readInt64();
            break;
          }
          case 56: {

            bytesRecv_ = input.readInt64();
            break;
          }
          case 64: {

            errIn_ = input.readInt64();
            break;
          }
          case 72: {

            dropIn_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_NetMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_NetMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.example.protobuf.NetMetrics.class, com.google.cloud.example.protobuf.NetMetrics.Builder.class);
  }

  public static final int INTERFACE_FIELD_NUMBER = 1;
  private volatile java.lang.Object interface_;
  /**
   * <code>string interface = 1;</code>
   */
  public java.lang.String getInterface() {
    java.lang.Object ref = interface_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interface_ = s;
      return s;
    }
  }
  /**
   * <code>string interface = 1;</code>
   */
  public com.google.protobuf.ByteString
      getInterfaceBytes() {
    java.lang.Object ref = interface_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERR_OUT_FIELD_NUMBER = 2;
  private long errOut_;
  /**
   * <code>int64 err_out = 2;</code>
   */
  public long getErrOut() {
    return errOut_;
  }

  public static final int BYTES_SENT_FIELD_NUMBER = 3;
  private long bytesSent_;
  /**
   * <code>int64 bytes_sent = 3;</code>
   */
  public long getBytesSent() {
    return bytesSent_;
  }

  public static final int PACKETS_SENT_FIELD_NUMBER = 4;
  private long packetsSent_;
  /**
   * <code>int64 packets_sent = 4;</code>
   */
  public long getPacketsSent() {
    return packetsSent_;
  }

  public static final int PACKETS_RECV_FIELD_NUMBER = 5;
  private long packetsRecv_;
  /**
   * <code>int64 packets_recv = 5;</code>
   */
  public long getPacketsRecv() {
    return packetsRecv_;
  }

  public static final int DROP_OUT_FIELD_NUMBER = 6;
  private long dropOut_;
  /**
   * <code>int64 drop_out = 6;</code>
   */
  public long getDropOut() {
    return dropOut_;
  }

  public static final int BYTES_RECV_FIELD_NUMBER = 7;
  private long bytesRecv_;
  /**
   * <code>int64 bytes_recv = 7;</code>
   */
  public long getBytesRecv() {
    return bytesRecv_;
  }

  public static final int ERR_IN_FIELD_NUMBER = 8;
  private long errIn_;
  /**
   * <code>int64 err_in = 8;</code>
   */
  public long getErrIn() {
    return errIn_;
  }

  public static final int DROP_IN_FIELD_NUMBER = 9;
  private long dropIn_;
  /**
   * <code>int64 drop_in = 9;</code>
   */
  public long getDropIn() {
    return dropIn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getInterfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, interface_);
    }
    if (errOut_ != 0L) {
      output.writeInt64(2, errOut_);
    }
    if (bytesSent_ != 0L) {
      output.writeInt64(3, bytesSent_);
    }
    if (packetsSent_ != 0L) {
      output.writeInt64(4, packetsSent_);
    }
    if (packetsRecv_ != 0L) {
      output.writeInt64(5, packetsRecv_);
    }
    if (dropOut_ != 0L) {
      output.writeInt64(6, dropOut_);
    }
    if (bytesRecv_ != 0L) {
      output.writeInt64(7, bytesRecv_);
    }
    if (errIn_ != 0L) {
      output.writeInt64(8, errIn_);
    }
    if (dropIn_ != 0L) {
      output.writeInt64(9, dropIn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getInterfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, interface_);
    }
    if (errOut_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, errOut_);
    }
    if (bytesSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, bytesSent_);
    }
    if (packetsSent_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, packetsSent_);
    }
    if (packetsRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, packetsRecv_);
    }
    if (dropOut_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, dropOut_);
    }
    if (bytesRecv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, bytesRecv_);
    }
    if (errIn_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, errIn_);
    }
    if (dropIn_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, dropIn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.example.protobuf.NetMetrics)) {
      return super.equals(obj);
    }
    com.google.cloud.example.protobuf.NetMetrics other = (com.google.cloud.example.protobuf.NetMetrics) obj;

    boolean result = true;
    result = result && getInterface()
        .equals(other.getInterface());
    result = result && (getErrOut()
        == other.getErrOut());
    result = result && (getBytesSent()
        == other.getBytesSent());
    result = result && (getPacketsSent()
        == other.getPacketsSent());
    result = result && (getPacketsRecv()
        == other.getPacketsRecv());
    result = result && (getDropOut()
        == other.getDropOut());
    result = result && (getBytesRecv()
        == other.getBytesRecv());
    result = result && (getErrIn()
        == other.getErrIn());
    result = result && (getDropIn()
        == other.getDropIn());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + getInterface().hashCode();
    hash = (37 * hash) + ERR_OUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getErrOut());
    hash = (37 * hash) + BYTES_SENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesSent());
    hash = (37 * hash) + PACKETS_SENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsSent());
    hash = (37 * hash) + PACKETS_RECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPacketsRecv());
    hash = (37 * hash) + DROP_OUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDropOut());
    hash = (37 * hash) + BYTES_RECV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBytesRecv());
    hash = (37 * hash) + ERR_IN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getErrIn());
    hash = (37 * hash) + DROP_IN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDropIn());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.NetMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.example.protobuf.NetMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.example.NetMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.example.NetMetrics)
      com.google.cloud.example.protobuf.NetMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_NetMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_NetMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.example.protobuf.NetMetrics.class, com.google.cloud.example.protobuf.NetMetrics.Builder.class);
    }

    // Construct using com.google.cloud.example.protobuf.NetMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      interface_ = "";

      errOut_ = 0L;

      bytesSent_ = 0L;

      packetsSent_ = 0L;

      packetsRecv_ = 0L;

      dropOut_ = 0L;

      bytesRecv_ = 0L;

      errIn_ = 0L;

      dropIn_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_NetMetrics_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.NetMetrics getDefaultInstanceForType() {
      return com.google.cloud.example.protobuf.NetMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.NetMetrics build() {
      com.google.cloud.example.protobuf.NetMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.NetMetrics buildPartial() {
      com.google.cloud.example.protobuf.NetMetrics result = new com.google.cloud.example.protobuf.NetMetrics(this);
      result.interface_ = interface_;
      result.errOut_ = errOut_;
      result.bytesSent_ = bytesSent_;
      result.packetsSent_ = packetsSent_;
      result.packetsRecv_ = packetsRecv_;
      result.dropOut_ = dropOut_;
      result.bytesRecv_ = bytesRecv_;
      result.errIn_ = errIn_;
      result.dropIn_ = dropIn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.example.protobuf.NetMetrics) {
        return mergeFrom((com.google.cloud.example.protobuf.NetMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.example.protobuf.NetMetrics other) {
      if (other == com.google.cloud.example.protobuf.NetMetrics.getDefaultInstance()) return this;
      if (!other.getInterface().isEmpty()) {
        interface_ = other.interface_;
        onChanged();
      }
      if (other.getErrOut() != 0L) {
        setErrOut(other.getErrOut());
      }
      if (other.getBytesSent() != 0L) {
        setBytesSent(other.getBytesSent());
      }
      if (other.getPacketsSent() != 0L) {
        setPacketsSent(other.getPacketsSent());
      }
      if (other.getPacketsRecv() != 0L) {
        setPacketsRecv(other.getPacketsRecv());
      }
      if (other.getDropOut() != 0L) {
        setDropOut(other.getDropOut());
      }
      if (other.getBytesRecv() != 0L) {
        setBytesRecv(other.getBytesRecv());
      }
      if (other.getErrIn() != 0L) {
        setErrIn(other.getErrIn());
      }
      if (other.getDropIn() != 0L) {
        setDropIn(other.getDropIn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.example.protobuf.NetMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.example.protobuf.NetMetrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object interface_ = "";
    /**
     * <code>string interface = 1;</code>
     */
    public java.lang.String getInterface() {
      java.lang.Object ref = interface_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interface_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interface = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceBytes() {
      java.lang.Object ref = interface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interface = 1;</code>
     */
    public Builder setInterface(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interface_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interface = 1;</code>
     */
    public Builder clearInterface() {
      
      interface_ = getDefaultInstance().getInterface();
      onChanged();
      return this;
    }
    /**
     * <code>string interface = 1;</code>
     */
    public Builder setInterfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interface_ = value;
      onChanged();
      return this;
    }

    private long errOut_ ;
    /**
     * <code>int64 err_out = 2;</code>
     */
    public long getErrOut() {
      return errOut_;
    }
    /**
     * <code>int64 err_out = 2;</code>
     */
    public Builder setErrOut(long value) {
      
      errOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 err_out = 2;</code>
     */
    public Builder clearErrOut() {
      
      errOut_ = 0L;
      onChanged();
      return this;
    }

    private long bytesSent_ ;
    /**
     * <code>int64 bytes_sent = 3;</code>
     */
    public long getBytesSent() {
      return bytesSent_;
    }
    /**
     * <code>int64 bytes_sent = 3;</code>
     */
    public Builder setBytesSent(long value) {
      
      bytesSent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytes_sent = 3;</code>
     */
    public Builder clearBytesSent() {
      
      bytesSent_ = 0L;
      onChanged();
      return this;
    }

    private long packetsSent_ ;
    /**
     * <code>int64 packets_sent = 4;</code>
     */
    public long getPacketsSent() {
      return packetsSent_;
    }
    /**
     * <code>int64 packets_sent = 4;</code>
     */
    public Builder setPacketsSent(long value) {
      
      packetsSent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packets_sent = 4;</code>
     */
    public Builder clearPacketsSent() {
      
      packetsSent_ = 0L;
      onChanged();
      return this;
    }

    private long packetsRecv_ ;
    /**
     * <code>int64 packets_recv = 5;</code>
     */
    public long getPacketsRecv() {
      return packetsRecv_;
    }
    /**
     * <code>int64 packets_recv = 5;</code>
     */
    public Builder setPacketsRecv(long value) {
      
      packetsRecv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 packets_recv = 5;</code>
     */
    public Builder clearPacketsRecv() {
      
      packetsRecv_ = 0L;
      onChanged();
      return this;
    }

    private long dropOut_ ;
    /**
     * <code>int64 drop_out = 6;</code>
     */
    public long getDropOut() {
      return dropOut_;
    }
    /**
     * <code>int64 drop_out = 6;</code>
     */
    public Builder setDropOut(long value) {
      
      dropOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 drop_out = 6;</code>
     */
    public Builder clearDropOut() {
      
      dropOut_ = 0L;
      onChanged();
      return this;
    }

    private long bytesRecv_ ;
    /**
     * <code>int64 bytes_recv = 7;</code>
     */
    public long getBytesRecv() {
      return bytesRecv_;
    }
    /**
     * <code>int64 bytes_recv = 7;</code>
     */
    public Builder setBytesRecv(long value) {
      
      bytesRecv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bytes_recv = 7;</code>
     */
    public Builder clearBytesRecv() {
      
      bytesRecv_ = 0L;
      onChanged();
      return this;
    }

    private long errIn_ ;
    /**
     * <code>int64 err_in = 8;</code>
     */
    public long getErrIn() {
      return errIn_;
    }
    /**
     * <code>int64 err_in = 8;</code>
     */
    public Builder setErrIn(long value) {
      
      errIn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 err_in = 8;</code>
     */
    public Builder clearErrIn() {
      
      errIn_ = 0L;
      onChanged();
      return this;
    }

    private long dropIn_ ;
    /**
     * <code>int64 drop_in = 9;</code>
     */
    public long getDropIn() {
      return dropIn_;
    }
    /**
     * <code>int64 drop_in = 9;</code>
     */
    public Builder setDropIn(long value) {
      
      dropIn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 drop_in = 9;</code>
     */
    public Builder clearDropIn() {
      
      dropIn_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.example.NetMetrics)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.example.NetMetrics)
  private static final com.google.cloud.example.protobuf.NetMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.example.protobuf.NetMetrics();
  }

  public static com.google.cloud.example.protobuf.NetMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetMetrics>
      PARSER = new com.google.protobuf.AbstractParser<NetMetrics>() {
    @java.lang.Override
    public NetMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetMetrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.example.protobuf.NetMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

