// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

public interface NetMetrics2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.example.NetMetrics2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string interface = 1;</code>
   */
  java.lang.String getInterface();
  /**
   * <code>string interface = 1;</code>
   */
  com.google.protobuf.ByteString
      getInterfaceBytes();

  /**
   * <code>int32 udp_rcvbuferrors = 2;</code>
   */
  int getUdpRcvbuferrors();

  /**
   * <code>int32 ip_indiscards = 3;</code>
   */
  int getIpIndiscards();

  /**
   * <code>int32 icmp_outtimestampreps = 4;</code>
   */
  int getIcmpOuttimestampreps();

  /**
   * <code>int32 icmp_outechos = 5;</code>
   */
  int getIcmpOutechos();

  /**
   * <code>int64 udp_ignoredmulti = 6;</code>
   */
  long getUdpIgnoredmulti();

  /**
   * <code>int32 udplite_outdatagrams = 7;</code>
   */
  int getUdpliteOutdatagrams();

  /**
   * <code>int32 ip_reasmtimeout = 8;</code>
   */
  int getIpReasmtimeout();

  /**
   * <code>int32 ip_fragoks = 9;</code>
   */
  int getIpFragoks();

  /**
   * <code>int32 icmp_inmsgs = 10;</code>
   */
  int getIcmpInmsgs();

  /**
   * <code>int32 udp_incsumerrors = 11;</code>
   */
  int getUdpIncsumerrors();

  /**
   * <code>int32 ip_reasmreqds = 12;</code>
   */
  int getIpReasmreqds();

  /**
   * <code>int32 icmp_outaddrmasks = 13;</code>
   */
  int getIcmpOutaddrmasks();

  /**
   * <code>int64 tcp_rtomax = 14;</code>
   */
  long getTcpRtomax();

  /**
   * <code>int32 udplite_rcvbuferrors = 15;</code>
   */
  int getUdpliteRcvbuferrors();

  /**
   * <code>int32 ip_reasmfails = 16;</code>
   */
  int getIpReasmfails();

  /**
   * <code>int32 tcp_maxconn = 17;</code>
   */
  int getTcpMaxconn();

  /**
   * <code>int32 tcp_rtomin = 18;</code>
   */
  int getTcpRtomin();

  /**
   * <code>int64 tcp_passiveopens = 19;</code>
   */
  long getTcpPassiveopens();

  /**
   * <code>int32 ip_fragcreates = 20;</code>
   */
  int getIpFragcreates();

  /**
   * <code>int32 icmp_incsumerrors = 21;</code>
   */
  int getIcmpIncsumerrors();

  /**
   * <code>int32 udplite_indatagrams = 22;</code>
   */
  int getUdpliteIndatagrams();

  /**
   * <code>int32 ip_reasmoks = 23;</code>
   */
  int getIpReasmoks();

  /**
   * <code>int32 icmp_intimeexcds = 24;</code>
   */
  int getIcmpIntimeexcds();

  /**
   * <code>int32 icmp_outtimeexcds = 25;</code>
   */
  int getIcmpOuttimeexcds();

  /**
   * <code>int32 tcp_inerrs = 26;</code>
   */
  int getTcpInerrs();

  /**
   * <code>int32 icmp_outaddrmaskreps = 27;</code>
   */
  int getIcmpOutaddrmaskreps();

  /**
   * <code>int32 icmpmsg_outtype = 28;</code>
   */
  int getIcmpmsgOuttype();

  /**
   * <code>int32 udp_noports = 29;</code>
   */
  int getUdpNoports();

  /**
   * <code>int32 icmpmsg_intype8 = 30;</code>
   */
  int getIcmpmsgIntype8();

  /**
   * <code>int64 tcp_insegs = 31;</code>
   */
  long getTcpInsegs();

  /**
   * <code>int32 udplite_noports = 32;</code>
   */
  int getUdpliteNoports();

  /**
   * <code>int32 ip_fragfails = 33;</code>
   */
  int getIpFragfails();

  /**
   * <code>int64 ip_indelivers = 34;</code>
   */
  long getIpIndelivers();

  /**
   * <code>int32 icmp_outtimestamps = 35;</code>
   */
  int getIcmpOuttimestamps();

  /**
   * <code>int32 icmp_outechoreps = 36;</code>
   */
  int getIcmpOutechoreps();

  /**
   * <code>int32 tcp_incsumerrors = 37;</code>
   */
  int getTcpIncsumerrors();

  /**
   * <code>int32 tcp_rtoalgorithm = 38;</code>
   */
  int getTcpRtoalgorithm();

  /**
   * <code>int32 ip_forwdatagrams = 39;</code>
   */
  int getIpForwdatagrams();

  /**
   * <code>int32 icmp_insrcquenchs = 40;</code>
   */
  int getIcmpInsrcquenchs();

  /**
   * <code>int32 icmp_outdestunreachs = 41;</code>
   */
  int getIcmpOutdestunreachs();

  /**
   * <code>int32 icmp_outparmprobs = 42;</code>
   */
  int getIcmpOutparmprobs();

  /**
   * <code>int32 ip_outnoroutes = 43;</code>
   */
  int getIpOutnoroutes();

  /**
   * <code>int32 icmp_inechoreps = 44;</code>
   */
  int getIcmpInechoreps();

  /**
   * <code>int32 udplite_inerrors = 45;</code>
   */
  int getUdpliteInerrors();

  /**
   * <code>int32 tcp_currestab = 46;</code>
   */
  int getTcpCurrestab();

  /**
   * <code>int32 ip_inunknownprotos = 47;</code>
   */
  int getIpInunknownprotos();

  /**
   * <code>int32 icmp_inechos = 48;</code>
   */
  int getIcmpInechos();

  /**
   * <code>int32 icmp_inparmprobs = 49;</code>
   */
  int getIcmpInparmprobs();

  /**
   * <code>int32 icmp_inerrors = 50;</code>
   */
  int getIcmpInerrors();

  /**
   * <code>int32 tcp_activeopens = 51;</code>
   */
  int getTcpActiveopens();

  /**
   * <code>int32 tcp_outrsts = 52;</code>
   */
  int getTcpOutrsts();

  /**
   * <code>int32 udplite_ignoredmulti = 53;</code>
   */
  int getUdpliteIgnoredmulti();

  /**
   * <code>int32 ip_forwarding = 54;</code>
   */
  int getIpForwarding();

  /**
   * <code>int64 ip_inreceives = 55;</code>
   */
  long getIpInreceives();

  /**
   * <code>int32 ip_outdiscards = 56;</code>
   */
  int getIpOutdiscards();

  /**
   * <code>int32 icmp_inredirects = 57;</code>
   */
  int getIcmpInredirects();

  /**
   * <code>int32 icmp_inaddrmaskreps = 58;</code>
   */
  int getIcmpInaddrmaskreps();

  /**
   * <code>int32 icmp_inaddrmasks = 59;</code>
   */
  int getIcmpInaddrmasks();

  /**
   * <code>int32 icmp_outerrors = 60;</code>
   */
  int getIcmpOuterrors();

  /**
   * <code>int64 tcp_outsegs = 61;</code>
   */
  long getTcpOutsegs();

  /**
   * <code>int32 ip_defaultttl = 62;</code>
   */
  int getIpDefaultttl();

  /**
   * <code>int32 ip_inaddrerrors = 63;</code>
   */
  int getIpInaddrerrors();

  /**
   * <code>int32 icmp_outsrcquenchs = 64;</code>
   */
  int getIcmpOutsrcquenchs();

  /**
   * <code>int32 icmp_outredirects = 65;</code>
   */
  int getIcmpOutredirects();

  /**
   * <code>int64 tcp_estabresets = 66;</code>
   */
  long getTcpEstabresets();

  /**
   * <code>int32 udplite_sndbuferrors = 67;</code>
   */
  int getUdpliteSndbuferrors();

  /**
   * <code>int64 ip_outrequests = 68;</code>
   */
  long getIpOutrequests();

  /**
   * <code>int32 icmp_outmsgs = 69;</code>
   */
  int getIcmpOutmsgs();

  /**
   * <code>int64 tcp_retranssegs = 70;</code>
   */
  long getTcpRetranssegs();

  /**
   * <code>int64 udp_outdatagrams = 71;</code>
   */
  long getUdpOutdatagrams();

  /**
   * <code>int32 udp_sndbuferrors = 72;</code>
   */
  int getUdpSndbuferrors();

  /**
   * <code>int32 icmp_intimestamps = 73;</code>
   */
  int getIcmpIntimestamps();

  /**
   * <code>int32 icmp_indestunreachs = 74;</code>
   */
  int getIcmpIndestunreachs();

  /**
   * <code>int32 icmpmsg_outtype0 = 75;</code>
   */
  int getIcmpmsgOuttype0();

  /**
   * <code>int32 udp_indatagrams = 76;</code>
   */
  int getUdpIndatagrams();

  /**
   * <code>int32 udp_inerrors = 77;</code>
   */
  int getUdpInerrors();

  /**
   * <code>int32 udplite_incsumerrors = 78;</code>
   */
  int getUdpliteIncsumerrors();

  /**
   * <code>int32 ip_inhdrerrors = 79;</code>
   */
  int getIpInhdrerrors();

  /**
   * <code>int32 icmp_intimestampreps = 80;</code>
   */
  int getIcmpIntimestampreps();

  /**
   * <code>int32 icmpmsg_intype3 = 81;</code>
   */
  int getIcmpmsgIntype3();

  /**
   * <code>int32 tcp_attemptfails = 82;</code>
   */
  int getTcpAttemptfails();
}
