// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/instancemetric.proto

package com.google.cloud.example.protobuf;

/**
 * Protobuf type {@code google.protobuf.example.VMMetrics}
 */
public  final class VMMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.example.VMMetrics)
    VMMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VMMetrics.newBuilder() to construct.
  private VMMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VMMetrics() {
    vmid_ = "";
    ip_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VMMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            vmid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 26: {
            com.google.cloud.example.protobuf.VMCPUMetrics.Builder subBuilder = null;
            if (cpu_ != null) {
              subBuilder = cpu_.toBuilder();
            }
            cpu_ = input.readMessage(com.google.cloud.example.protobuf.VMCPUMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cpu_);
              cpu_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.cloud.example.protobuf.VMDiskMetrics.Builder subBuilder = null;
            if (disk_ != null) {
              subBuilder = disk_.toBuilder();
            }
            disk_ = input.readMessage(com.google.cloud.example.protobuf.VMDiskMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(disk_);
              disk_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.cloud.example.protobuf.VMMemMetrics.Builder subBuilder = null;
            if (mem_ != null) {
              subBuilder = mem_.toBuilder();
            }
            mem_ = input.readMessage(com.google.cloud.example.protobuf.VMMemMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mem_);
              mem_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.cloud.example.protobuf.VMNetMetrics.Builder subBuilder = null;
            if (net_ != null) {
              subBuilder = net_.toBuilder();
            }
            net_ = input.readMessage(com.google.cloud.example.protobuf.VMNetMetrics.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(net_);
              net_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_VMMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_VMMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.example.protobuf.VMMetrics.class, com.google.cloud.example.protobuf.VMMetrics.Builder.class);
  }

  public static final int VMID_FIELD_NUMBER = 1;
  private volatile java.lang.Object vmid_;
  /**
   * <code>string vmid = 1;</code>
   */
  public java.lang.String getVmid() {
    java.lang.Object ref = vmid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vmid_ = s;
      return s;
    }
  }
  /**
   * <code>string vmid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVmidBytes() {
    java.lang.Object ref = vmid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vmid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 2;
  private volatile java.lang.Object ip_;
  /**
   * <code>string ip = 2;</code>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_FIELD_NUMBER = 3;
  private com.google.cloud.example.protobuf.VMCPUMetrics cpu_;
  /**
   * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
   */
  public boolean hasCpu() {
    return cpu_ != null;
  }
  /**
   * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
   */
  public com.google.cloud.example.protobuf.VMCPUMetrics getCpu() {
    return cpu_ == null ? com.google.cloud.example.protobuf.VMCPUMetrics.getDefaultInstance() : cpu_;
  }
  /**
   * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
   */
  public com.google.cloud.example.protobuf.VMCPUMetricsOrBuilder getCpuOrBuilder() {
    return getCpu();
  }

  public static final int DISK_FIELD_NUMBER = 4;
  private com.google.cloud.example.protobuf.VMDiskMetrics disk_;
  /**
   * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
   */
  public boolean hasDisk() {
    return disk_ != null;
  }
  /**
   * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
   */
  public com.google.cloud.example.protobuf.VMDiskMetrics getDisk() {
    return disk_ == null ? com.google.cloud.example.protobuf.VMDiskMetrics.getDefaultInstance() : disk_;
  }
  /**
   * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
   */
  public com.google.cloud.example.protobuf.VMDiskMetricsOrBuilder getDiskOrBuilder() {
    return getDisk();
  }

  public static final int MEM_FIELD_NUMBER = 5;
  private com.google.cloud.example.protobuf.VMMemMetrics mem_;
  /**
   * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
   */
  public boolean hasMem() {
    return mem_ != null;
  }
  /**
   * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
   */
  public com.google.cloud.example.protobuf.VMMemMetrics getMem() {
    return mem_ == null ? com.google.cloud.example.protobuf.VMMemMetrics.getDefaultInstance() : mem_;
  }
  /**
   * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
   */
  public com.google.cloud.example.protobuf.VMMemMetricsOrBuilder getMemOrBuilder() {
    return getMem();
  }

  public static final int NET_FIELD_NUMBER = 6;
  private com.google.cloud.example.protobuf.VMNetMetrics net_;
  /**
   * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
   */
  public boolean hasNet() {
    return net_ != null;
  }
  /**
   * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
   */
  public com.google.cloud.example.protobuf.VMNetMetrics getNet() {
    return net_ == null ? com.google.cloud.example.protobuf.VMNetMetrics.getDefaultInstance() : net_;
  }
  /**
   * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
   */
  public com.google.cloud.example.protobuf.VMNetMetricsOrBuilder getNetOrBuilder() {
    return getNet();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getVmidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vmid_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
    }
    if (cpu_ != null) {
      output.writeMessage(3, getCpu());
    }
    if (disk_ != null) {
      output.writeMessage(4, getDisk());
    }
    if (mem_ != null) {
      output.writeMessage(5, getMem());
    }
    if (net_ != null) {
      output.writeMessage(6, getNet());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVmidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vmid_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
    }
    if (cpu_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCpu());
    }
    if (disk_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDisk());
    }
    if (mem_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMem());
    }
    if (net_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getNet());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.example.protobuf.VMMetrics)) {
      return super.equals(obj);
    }
    com.google.cloud.example.protobuf.VMMetrics other = (com.google.cloud.example.protobuf.VMMetrics) obj;

    boolean result = true;
    result = result && getVmid()
        .equals(other.getVmid());
    result = result && getIp()
        .equals(other.getIp());
    result = result && (hasCpu() == other.hasCpu());
    if (hasCpu()) {
      result = result && getCpu()
          .equals(other.getCpu());
    }
    result = result && (hasDisk() == other.hasDisk());
    if (hasDisk()) {
      result = result && getDisk()
          .equals(other.getDisk());
    }
    result = result && (hasMem() == other.hasMem());
    if (hasMem()) {
      result = result && getMem()
          .equals(other.getMem());
    }
    result = result && (hasNet() == other.hasNet());
    if (hasNet()) {
      result = result && getNet()
          .equals(other.getNet());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VMID_FIELD_NUMBER;
    hash = (53 * hash) + getVmid().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    if (hasCpu()) {
      hash = (37 * hash) + CPU_FIELD_NUMBER;
      hash = (53 * hash) + getCpu().hashCode();
    }
    if (hasDisk()) {
      hash = (37 * hash) + DISK_FIELD_NUMBER;
      hash = (53 * hash) + getDisk().hashCode();
    }
    if (hasMem()) {
      hash = (37 * hash) + MEM_FIELD_NUMBER;
      hash = (53 * hash) + getMem().hashCode();
    }
    if (hasNet()) {
      hash = (37 * hash) + NET_FIELD_NUMBER;
      hash = (53 * hash) + getNet().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.example.protobuf.VMMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.example.protobuf.VMMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.example.VMMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.example.VMMetrics)
      com.google.cloud.example.protobuf.VMMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_VMMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_VMMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.example.protobuf.VMMetrics.class, com.google.cloud.example.protobuf.VMMetrics.Builder.class);
    }

    // Construct using com.google.cloud.example.protobuf.VMMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vmid_ = "";

      ip_ = "";

      if (cpuBuilder_ == null) {
        cpu_ = null;
      } else {
        cpu_ = null;
        cpuBuilder_ = null;
      }
      if (diskBuilder_ == null) {
        disk_ = null;
      } else {
        disk_ = null;
        diskBuilder_ = null;
      }
      if (memBuilder_ == null) {
        mem_ = null;
      } else {
        mem_ = null;
        memBuilder_ = null;
      }
      if (netBuilder_ == null) {
        net_ = null;
      } else {
        net_ = null;
        netBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.example.protobuf.MetricsProto.internal_static_google_protobuf_example_VMMetrics_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.VMMetrics getDefaultInstanceForType() {
      return com.google.cloud.example.protobuf.VMMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.VMMetrics build() {
      com.google.cloud.example.protobuf.VMMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.example.protobuf.VMMetrics buildPartial() {
      com.google.cloud.example.protobuf.VMMetrics result = new com.google.cloud.example.protobuf.VMMetrics(this);
      result.vmid_ = vmid_;
      result.ip_ = ip_;
      if (cpuBuilder_ == null) {
        result.cpu_ = cpu_;
      } else {
        result.cpu_ = cpuBuilder_.build();
      }
      if (diskBuilder_ == null) {
        result.disk_ = disk_;
      } else {
        result.disk_ = diskBuilder_.build();
      }
      if (memBuilder_ == null) {
        result.mem_ = mem_;
      } else {
        result.mem_ = memBuilder_.build();
      }
      if (netBuilder_ == null) {
        result.net_ = net_;
      } else {
        result.net_ = netBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.example.protobuf.VMMetrics) {
        return mergeFrom((com.google.cloud.example.protobuf.VMMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.example.protobuf.VMMetrics other) {
      if (other == com.google.cloud.example.protobuf.VMMetrics.getDefaultInstance()) return this;
      if (!other.getVmid().isEmpty()) {
        vmid_ = other.vmid_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (other.hasCpu()) {
        mergeCpu(other.getCpu());
      }
      if (other.hasDisk()) {
        mergeDisk(other.getDisk());
      }
      if (other.hasMem()) {
        mergeMem(other.getMem());
      }
      if (other.hasNet()) {
        mergeNet(other.getNet());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.example.protobuf.VMMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.example.protobuf.VMMetrics) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object vmid_ = "";
    /**
     * <code>string vmid = 1;</code>
     */
    public java.lang.String getVmid() {
      java.lang.Object ref = vmid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vmid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vmid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVmidBytes() {
      java.lang.Object ref = vmid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vmid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vmid = 1;</code>
     */
    public Builder setVmid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      vmid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vmid = 1;</code>
     */
    public Builder clearVmid() {
      
      vmid_ = getDefaultInstance().getVmid();
      onChanged();
      return this;
    }
    /**
     * <code>string vmid = 1;</code>
     */
    public Builder setVmidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      vmid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 2;</code>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 2;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 2;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private com.google.cloud.example.protobuf.VMCPUMetrics cpu_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMCPUMetrics, com.google.cloud.example.protobuf.VMCPUMetrics.Builder, com.google.cloud.example.protobuf.VMCPUMetricsOrBuilder> cpuBuilder_;
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public boolean hasCpu() {
      return cpuBuilder_ != null || cpu_ != null;
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public com.google.cloud.example.protobuf.VMCPUMetrics getCpu() {
      if (cpuBuilder_ == null) {
        return cpu_ == null ? com.google.cloud.example.protobuf.VMCPUMetrics.getDefaultInstance() : cpu_;
      } else {
        return cpuBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public Builder setCpu(com.google.cloud.example.protobuf.VMCPUMetrics value) {
      if (cpuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cpu_ = value;
        onChanged();
      } else {
        cpuBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public Builder setCpu(
        com.google.cloud.example.protobuf.VMCPUMetrics.Builder builderForValue) {
      if (cpuBuilder_ == null) {
        cpu_ = builderForValue.build();
        onChanged();
      } else {
        cpuBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public Builder mergeCpu(com.google.cloud.example.protobuf.VMCPUMetrics value) {
      if (cpuBuilder_ == null) {
        if (cpu_ != null) {
          cpu_ =
            com.google.cloud.example.protobuf.VMCPUMetrics.newBuilder(cpu_).mergeFrom(value).buildPartial();
        } else {
          cpu_ = value;
        }
        onChanged();
      } else {
        cpuBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public Builder clearCpu() {
      if (cpuBuilder_ == null) {
        cpu_ = null;
        onChanged();
      } else {
        cpu_ = null;
        cpuBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public com.google.cloud.example.protobuf.VMCPUMetrics.Builder getCpuBuilder() {
      
      onChanged();
      return getCpuFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    public com.google.cloud.example.protobuf.VMCPUMetricsOrBuilder getCpuOrBuilder() {
      if (cpuBuilder_ != null) {
        return cpuBuilder_.getMessageOrBuilder();
      } else {
        return cpu_ == null ?
            com.google.cloud.example.protobuf.VMCPUMetrics.getDefaultInstance() : cpu_;
      }
    }
    /**
     * <code>.google.protobuf.example.VMCPUMetrics cpu = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMCPUMetrics, com.google.cloud.example.protobuf.VMCPUMetrics.Builder, com.google.cloud.example.protobuf.VMCPUMetricsOrBuilder> 
        getCpuFieldBuilder() {
      if (cpuBuilder_ == null) {
        cpuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.VMCPUMetrics, com.google.cloud.example.protobuf.VMCPUMetrics.Builder, com.google.cloud.example.protobuf.VMCPUMetricsOrBuilder>(
                getCpu(),
                getParentForChildren(),
                isClean());
        cpu_ = null;
      }
      return cpuBuilder_;
    }

    private com.google.cloud.example.protobuf.VMDiskMetrics disk_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMDiskMetrics, com.google.cloud.example.protobuf.VMDiskMetrics.Builder, com.google.cloud.example.protobuf.VMDiskMetricsOrBuilder> diskBuilder_;
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public boolean hasDisk() {
      return diskBuilder_ != null || disk_ != null;
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMDiskMetrics getDisk() {
      if (diskBuilder_ == null) {
        return disk_ == null ? com.google.cloud.example.protobuf.VMDiskMetrics.getDefaultInstance() : disk_;
      } else {
        return diskBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public Builder setDisk(com.google.cloud.example.protobuf.VMDiskMetrics value) {
      if (diskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        disk_ = value;
        onChanged();
      } else {
        diskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public Builder setDisk(
        com.google.cloud.example.protobuf.VMDiskMetrics.Builder builderForValue) {
      if (diskBuilder_ == null) {
        disk_ = builderForValue.build();
        onChanged();
      } else {
        diskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public Builder mergeDisk(com.google.cloud.example.protobuf.VMDiskMetrics value) {
      if (diskBuilder_ == null) {
        if (disk_ != null) {
          disk_ =
            com.google.cloud.example.protobuf.VMDiskMetrics.newBuilder(disk_).mergeFrom(value).buildPartial();
        } else {
          disk_ = value;
        }
        onChanged();
      } else {
        diskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public Builder clearDisk() {
      if (diskBuilder_ == null) {
        disk_ = null;
        onChanged();
      } else {
        disk_ = null;
        diskBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMDiskMetrics.Builder getDiskBuilder() {
      
      onChanged();
      return getDiskFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    public com.google.cloud.example.protobuf.VMDiskMetricsOrBuilder getDiskOrBuilder() {
      if (diskBuilder_ != null) {
        return diskBuilder_.getMessageOrBuilder();
      } else {
        return disk_ == null ?
            com.google.cloud.example.protobuf.VMDiskMetrics.getDefaultInstance() : disk_;
      }
    }
    /**
     * <code>.google.protobuf.example.VMDiskMetrics disk = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMDiskMetrics, com.google.cloud.example.protobuf.VMDiskMetrics.Builder, com.google.cloud.example.protobuf.VMDiskMetricsOrBuilder> 
        getDiskFieldBuilder() {
      if (diskBuilder_ == null) {
        diskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.VMDiskMetrics, com.google.cloud.example.protobuf.VMDiskMetrics.Builder, com.google.cloud.example.protobuf.VMDiskMetricsOrBuilder>(
                getDisk(),
                getParentForChildren(),
                isClean());
        disk_ = null;
      }
      return diskBuilder_;
    }

    private com.google.cloud.example.protobuf.VMMemMetrics mem_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMMemMetrics, com.google.cloud.example.protobuf.VMMemMetrics.Builder, com.google.cloud.example.protobuf.VMMemMetricsOrBuilder> memBuilder_;
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public boolean hasMem() {
      return memBuilder_ != null || mem_ != null;
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public com.google.cloud.example.protobuf.VMMemMetrics getMem() {
      if (memBuilder_ == null) {
        return mem_ == null ? com.google.cloud.example.protobuf.VMMemMetrics.getDefaultInstance() : mem_;
      } else {
        return memBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public Builder setMem(com.google.cloud.example.protobuf.VMMemMetrics value) {
      if (memBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mem_ = value;
        onChanged();
      } else {
        memBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public Builder setMem(
        com.google.cloud.example.protobuf.VMMemMetrics.Builder builderForValue) {
      if (memBuilder_ == null) {
        mem_ = builderForValue.build();
        onChanged();
      } else {
        memBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public Builder mergeMem(com.google.cloud.example.protobuf.VMMemMetrics value) {
      if (memBuilder_ == null) {
        if (mem_ != null) {
          mem_ =
            com.google.cloud.example.protobuf.VMMemMetrics.newBuilder(mem_).mergeFrom(value).buildPartial();
        } else {
          mem_ = value;
        }
        onChanged();
      } else {
        memBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public Builder clearMem() {
      if (memBuilder_ == null) {
        mem_ = null;
        onChanged();
      } else {
        mem_ = null;
        memBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public com.google.cloud.example.protobuf.VMMemMetrics.Builder getMemBuilder() {
      
      onChanged();
      return getMemFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    public com.google.cloud.example.protobuf.VMMemMetricsOrBuilder getMemOrBuilder() {
      if (memBuilder_ != null) {
        return memBuilder_.getMessageOrBuilder();
      } else {
        return mem_ == null ?
            com.google.cloud.example.protobuf.VMMemMetrics.getDefaultInstance() : mem_;
      }
    }
    /**
     * <code>.google.protobuf.example.VMMemMetrics mem = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMMemMetrics, com.google.cloud.example.protobuf.VMMemMetrics.Builder, com.google.cloud.example.protobuf.VMMemMetricsOrBuilder> 
        getMemFieldBuilder() {
      if (memBuilder_ == null) {
        memBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.VMMemMetrics, com.google.cloud.example.protobuf.VMMemMetrics.Builder, com.google.cloud.example.protobuf.VMMemMetricsOrBuilder>(
                getMem(),
                getParentForChildren(),
                isClean());
        mem_ = null;
      }
      return memBuilder_;
    }

    private com.google.cloud.example.protobuf.VMNetMetrics net_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMNetMetrics, com.google.cloud.example.protobuf.VMNetMetrics.Builder, com.google.cloud.example.protobuf.VMNetMetricsOrBuilder> netBuilder_;
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public boolean hasNet() {
      return netBuilder_ != null || net_ != null;
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public com.google.cloud.example.protobuf.VMNetMetrics getNet() {
      if (netBuilder_ == null) {
        return net_ == null ? com.google.cloud.example.protobuf.VMNetMetrics.getDefaultInstance() : net_;
      } else {
        return netBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public Builder setNet(com.google.cloud.example.protobuf.VMNetMetrics value) {
      if (netBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        net_ = value;
        onChanged();
      } else {
        netBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public Builder setNet(
        com.google.cloud.example.protobuf.VMNetMetrics.Builder builderForValue) {
      if (netBuilder_ == null) {
        net_ = builderForValue.build();
        onChanged();
      } else {
        netBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public Builder mergeNet(com.google.cloud.example.protobuf.VMNetMetrics value) {
      if (netBuilder_ == null) {
        if (net_ != null) {
          net_ =
            com.google.cloud.example.protobuf.VMNetMetrics.newBuilder(net_).mergeFrom(value).buildPartial();
        } else {
          net_ = value;
        }
        onChanged();
      } else {
        netBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public Builder clearNet() {
      if (netBuilder_ == null) {
        net_ = null;
        onChanged();
      } else {
        net_ = null;
        netBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public com.google.cloud.example.protobuf.VMNetMetrics.Builder getNetBuilder() {
      
      onChanged();
      return getNetFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    public com.google.cloud.example.protobuf.VMNetMetricsOrBuilder getNetOrBuilder() {
      if (netBuilder_ != null) {
        return netBuilder_.getMessageOrBuilder();
      } else {
        return net_ == null ?
            com.google.cloud.example.protobuf.VMNetMetrics.getDefaultInstance() : net_;
      }
    }
    /**
     * <code>.google.protobuf.example.VMNetMetrics net = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.cloud.example.protobuf.VMNetMetrics, com.google.cloud.example.protobuf.VMNetMetrics.Builder, com.google.cloud.example.protobuf.VMNetMetricsOrBuilder> 
        getNetFieldBuilder() {
      if (netBuilder_ == null) {
        netBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.example.protobuf.VMNetMetrics, com.google.cloud.example.protobuf.VMNetMetrics.Builder, com.google.cloud.example.protobuf.VMNetMetricsOrBuilder>(
                getNet(),
                getParentForChildren(),
                isClean());
        net_ = null;
      }
      return netBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.example.VMMetrics)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.example.VMMetrics)
  private static final com.google.cloud.example.protobuf.VMMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.example.protobuf.VMMetrics();
  }

  public static com.google.cloud.example.protobuf.VMMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VMMetrics>
      PARSER = new com.google.protobuf.AbstractParser<VMMetrics>() {
    @java.lang.Override
    public VMMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VMMetrics(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VMMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VMMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.example.protobuf.VMMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

