CREATE TABLE `Parent` (
  ParentId INT64 NOT NULL,
) PRIMARY KEY (ParentId);

CREATE TABLE Child01 (
  ParentId INT64 NOT NULL,
  Child01Id INT64 NOT NULL,
) PRIMARY KEY (ParentId, Child01Id),
  INTERLEAVE IN PARENT `Parent` ON DELETE CASCADE;

CREATE TABLE Child02 (
  ParentId INT64 NOT NULL,
  Child02Id INT64 NOT NULL,
) PRIMARY KEY (ParentId, Child02Id),
  INTERLEAVE IN PARENT `Parent` ON DELETE CASCADE;

CREATE TABLE Child03 (
  ParentId INT64 NOT NULL,
  Child03Id INT64 NOT NULL,
) PRIMARY KEY (ParentId, Child03Id),
  INTERLEAVE IN PARENT `Parent` ON DELETE CASCADE;

CREATE TABLE Child04 (
  ParentId INT64 NOT NULL,
  Child04Id INT64 NOT NULL,
) PRIMARY KEY (ParentId, Child04Id),
  INTERLEAVE IN PARENT `Parent` ON DELETE CASCADE
