project = "gcp-project-id"
history-bucket  = "history-bucket-name"
history-server = "history-server"
history-region = "us-central1"
network = "network-name"
hadoop-subnet = "hadoop-subnet-name"
hadoop-cidr-range = "10.0.0.0/19"
data-eng-cidr-range = "0.0.0.0/32"
