# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Remove previous docker versions [Ubuntu]
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent
    autoremove: yes
  when: os_type == "ubuntu"
  
- name: Update apt package manager [Ubuntu]
  apt:
    update_cache: yes
  when: os_type == "ubuntu"

- name: install docker and containerd [Ubuntu]
  apt:
    pkg:
    - containerd        
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - docker.io
    state: present
  when: os_type == "ubuntu"

- name: Remove previous docker versions [RHEL/CentOS]
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
    autoremove: yes
  when: os_type == "rhel"

- name: Remove podman-manpages [RHEL/CentOS]
  dnf:
    name: podman-manpages
    state: absent
    autoremove: yes
  when: os_type == "rhel"

#- name: Install yum-utils
#  dnf:
#    name: yum-utils
#    state: present
#  when: os_type == "rhel"

- name: Add docker-ce repo [RHEL/CentOS]
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    warn: false
  when: os_type == "rhel"

- name: Install docker-ce [RHEL/CentOS]
  dnf:
    name:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    state: present
  when: os_type == "rhel"

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: add anthos user to docker group
  ansible.builtin.user:
    name: "{{ login_user }}"
    groups: docker
    append: yes

- name: Start/Restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
