# This Dockerfile is used to build a custom cloud builder, shown in step 3 of README.md
# It pulls the public python 3 image and then installs virtualenv so that a virtual environment can
# be used to carry build steps forward.

FROM python:3

RUN pip install virtualenv