# This Dockerfile is used to build a custom cloud builder, shown in step 3 of README.md.
# It pulls the public Python 3 image from Dockerhub (https://hub.docker.com/_/python)and then installs virtualenv so
# that a virtual environment can be used to carry build steps forward.

FROM python:3

RUN pip install virtualenv