#!/bin/bash
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
/etc/hadoop/conf/core-site.xml
/etc/hadoop/conf/hdfs-site.xml
/etc/hadoop/conf/mapred-site.xml
/etc/hadoop/conf/nodes_include
/etc/hadoop/conf/yarn-site.xml
/etc/hive/conf/hive-site.xml
/etc/spark/conf/spark-defaults.conf
/etc/tez/conf/tez-site.xml
/etc/zookeeper/conf/zoo.cfg
/etc/alternatives/hadoop-conf/core-site.xml
/etc/alternatives/hadoop-conf/hdfs-site.xml
/etc/alternatives/hadoop-conf/mapred-site.xml
/etc/alternatives/hadoop-conf/nodes_include
/etc/alternatives/hadoop-conf/yarn-site.xml
/etc/alternatives/hive-conf/hive-site.xml
/etc/alternatives/spark-conf/spark-defaults.conf
/etc/alternatives/zookeeper-conf/zoo.cfg
/etc/hadoop/conf.empty/core-site.xml
/etc/hadoop/conf.empty/hdfs-site.xml
/etc/hadoop/conf.empty/mapred-site.xml
/etc/hadoop/conf.empty/nodes_include
/etc/hadoop/conf.empty/yarn-site.xml
/etc/hive/conf.dist/hive-site.xml
/etc/spark/conf.dist/spark-defaults.conf
/etc/zookeeper/conf.dist/zoo.cfg