custom.cloudbuildDisableWorkerPoolExternalIP:
  action_type: DENY
  condition: (resource.privatePoolV1Config.networkConfig.egressOption != "NO_PUBLIC_EGRESS")
  description: Ensure no unauthorized worker pools external ip used for each build
  display_name: Deny unauthorized worker pools external ip used for each build
  method_types:
  - CREATE
  - UPDATE
  resource_types:
  - cloudbuild.googleapis.com/WorkerPool
