/*
 * Copyright 2020 Google Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/policycache.proto

package com.google.cloud.storage.iam;

public final class PolicyCacheProto {
  private PolicyCacheProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_util_PolicyCache_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_util_PolicyCache_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_util_PolicyCache_Hash_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_util_PolicyCache_Hash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_util_PolicyCache_BucketEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_util_PolicyCache_BucketEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/policycache.proto\022\024google.protob" +
      "uf.util\"\341\001\n\013PolicyCache\022\021\n\ttimestamp\030\001 \001" +
      "(\003\022=\n\006bucket\030\002 \003(\0132-.google.protobuf.uti" +
      "l.PolicyCache.BucketEntry\032)\n\004Hash\022\021\n\ttim" +
      "estamp\030\001 \001(\003\022\016\n\006sha256\030\002 \001(\t\032U\n\013BucketEn" +
      "try\022\013\n\003key\030\001 \001(\t\0225\n\005value\030\002 \001(\0132&.google" +
      ".protobuf.util.PolicyCache.Hash:\0028\001B/\n\031c" +
      "om.google.cloud.util.bpmB\020PolicyCachePro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_util_PolicyCache_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_util_PolicyCache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_util_PolicyCache_descriptor,
        new java.lang.String[] { "Timestamp", "Bucket", });
    internal_static_google_protobuf_util_PolicyCache_Hash_descriptor =
      internal_static_google_protobuf_util_PolicyCache_descriptor.getNestedTypes().get(0);
    internal_static_google_protobuf_util_PolicyCache_Hash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_util_PolicyCache_Hash_descriptor,
        new java.lang.String[] { "Timestamp", "Sha256", });
    internal_static_google_protobuf_util_PolicyCache_BucketEntry_descriptor =
      internal_static_google_protobuf_util_PolicyCache_descriptor.getNestedTypes().get(1);
    internal_static_google_protobuf_util_PolicyCache_BucketEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_util_PolicyCache_BucketEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
