FROM java
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/server-1.0-SNAPSHOT-jar-with-dependencies.jar"]

ADD target/server-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/share/server-1.0-SNAPSHOT-jar-with-dependencies.jar
