# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'VERSION=0.5.23', '--pull', '--tag=gcr.io/$PROJECT_ID/earthly', '.']
- name: 'gcr.io/$PROJECT_ID/earthly'
  args: ['--version']

images: ['gcr.io/$PROJECT_ID/earthly']
tags: ['cloud-builders-community']
