/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as AdvisorVoiceOnlyRouteImport } from './routes/advisor.voice-only'
import { Route as AdvisorHeygenRouteImport } from './routes/advisor.heygen'
import { Route as AdvisorGoogle1pRouteImport } from './routes/advisor.google-1p'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorVoiceOnlyRoute = AdvisorVoiceOnlyRouteImport.update({
  id: '/voice-only',
  path: '/voice-only',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorHeygenRoute = AdvisorHeygenRouteImport.update({
  id: '/heygen',
  path: '/heygen',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorGoogle1pRoute = AdvisorGoogle1pRouteImport.update({
  id: '/google-1p',
  path: '/google-1p',
  getParentRoute: () => AdvisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/advisor/google-1p': typeof AdvisorGoogle1pRoute
  '/advisor/heygen': typeof AdvisorHeygenRoute
  '/advisor/voice-only': typeof AdvisorVoiceOnlyRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/advisor/google-1p': typeof AdvisorGoogle1pRoute
  '/advisor/heygen': typeof AdvisorHeygenRoute
  '/advisor/voice-only': typeof AdvisorVoiceOnlyRoute
  '/advisor': typeof AdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/advisor/google-1p': typeof AdvisorGoogle1pRoute
  '/advisor/heygen': typeof AdvisorHeygenRoute
  '/advisor/voice-only': typeof AdvisorVoiceOnlyRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/dashboard'
    | '/login'
    | '/advisor/google-1p'
    | '/advisor/heygen'
    | '/advisor/voice-only'
    | '/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/advisor/google-1p'
    | '/advisor/heygen'
    | '/advisor/voice-only'
    | '/advisor'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/dashboard'
    | '/login'
    | '/advisor/google-1p'
    | '/advisor/heygen'
    | '/advisor/voice-only'
    | '/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/voice-only': {
      id: '/advisor/voice-only'
      path: '/voice-only'
      fullPath: '/advisor/voice-only'
      preLoaderRoute: typeof AdvisorVoiceOnlyRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/heygen': {
      id: '/advisor/heygen'
      path: '/heygen'
      fullPath: '/advisor/heygen'
      preLoaderRoute: typeof AdvisorHeygenRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/google-1p': {
      id: '/advisor/google-1p'
      path: '/google-1p'
      fullPath: '/advisor/google-1p'
      preLoaderRoute: typeof AdvisorGoogle1pRouteImport
      parentRoute: typeof AdvisorRoute
    }
  }
}

interface AdvisorRouteChildren {
  AdvisorGoogle1pRoute: typeof AdvisorGoogle1pRoute
  AdvisorHeygenRoute: typeof AdvisorHeygenRoute
  AdvisorVoiceOnlyRoute: typeof AdvisorVoiceOnlyRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorGoogle1pRoute: AdvisorGoogle1pRoute,
  AdvisorHeygenRoute: AdvisorHeygenRoute,
  AdvisorVoiceOnlyRoute: AdvisorVoiceOnlyRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
