# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--source'
    - '.'
    - '--region'
    - '${_GOOGLE_CLOUD_LOCATION}'
    - '--project'
    - '${_GOOGLE_CLOUD_PROJECT}'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT},GOOGLE_CLOUD_LOCATION=${_GOOGLE_CLOUD_LOCATION},GOOGLE_GENAI_USE_VERTEXAI=FALSE,GOOGLE_API_KEY=${_GOOGLE_API_KEY},VERTEX_AI_RAG_CORPUS_ID=${_VERTEX_AI_RAG_CORPUS_ID}'

# Default substitution values
# You can override these when starting a build, e.g.,
# gcloud builds submit --config cloudbuild.yaml --substitutions=_SERVICE_NAME=my-new-service
substitutions:
  _GOOGLE_CLOUD_PROJECT: 'agents-stg'
  _GOOGLE_CLOUD_LOCATION: 'us-central1'
  _SERVICE_NAME: 'mosaic-rag-agent-backend'
  # 🚨 Important: It is strongly recommended to use Secret Manager for API keys
  # rather than passing them as plain text substitutions.
  _GOOGLE_API_KEY: '<>'
  _VERTEX_AI_RAG_CORPUS_ID: 'projects/428871167882/locations/us-central1/ragCorpora/645140646620823552'
