# Copyright 2022 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfile is to create an Image used by launcher to
# launch Dataflow workers.

FROM gcr.io/dataflow-templates-base/python38-template-launcher-base:20220418_RC00

ARG WORKDIR=/dataflow/template

RUN mkdir -p ${WORKDIR}

WORKDIR ${WORKDIR}

COPY requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY df-package/ .

RUN python setup.py install

ENV FLEX_TEMPLATE_PYTHON_PY_FILE="${WORKDIR}/main.py"



