# This Dockerfile is to create an Image used by launcher to
# launch Dataflow workers.

FROM gcr.io/dataflow-templates-base/python38-template-launcher-base:20220418_RC00

ARG WORKDIR=/dataflow/template

RUN mkdir -p ${WORKDIR}

WORKDIR ${WORKDIR}

COPY requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY df-package/ .

RUN python setup.py install

ENV FLEX_TEMPLATE_PYTHON_PY_FILE="${WORKDIR}/main.py"


