# Copyright 2022 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This software is provided as-is,
# without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.


# This Dockerfile is for creating an Image installed with all
# dependencies that will be used by Dataflow workers at run time.

FROM apache/beam_python3.8_sdk:2.40.0

COPY requirements.txt /tmp/

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r /tmp/requirements.txt

ARG WORKDIR=/dataflow/

RUN mkdir -p ${WORKDIR}

WORKDIR ${WORKDIR}

COPY df-package/ .

RUN python setup.py install


