module "kafka-connect-mm2" {
  source = "../../../modules/google-managed-kafkaconnect-mirror-maker2"
  project_id = "test-sandbox"
  region = "us-central1"
  zone = "us-central1-a"
  mkc_cluster_name = "mkc-mm2-tf"
  mkc_dest_cluster_id = "kafka-dest-new"
  mkc_src_cluster_id = "kafka-src-new"
  gmk_src_region = "us-central1"
  gmk_dst_region = "us-central1"                            
  shared_vpc_name = ""
  shared_vpc_subnetwork = ""                            
  service_account_email = "compute@developer.gserviceaccount.com"
  kafka_cluster_src_broker = "bootstrap.kafka-src-new.us-central1.managedkafka.test-sandbox.cloud.goog:9092"
  kafka_cluster_dest_broker = "bootstrap.kafka-dest-new.us-central1.managedkafka.test-sandbox.cloud.goog:9092"
}