steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PROFILE=claude_api'
      - '--target'
      - 'app-image'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:claudeapi'
      - '.'
    id: 'Build Claude API Docker Image'
    waitFor: ['-']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PROFILE=gemini'
      - '--build-arg'
      - 'GCP_PROJECT=$PROJECT_ID'
      - '--target'
      - 'app-image'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:gemini'
      - '.'
    id: 'Build Gemini on VertexAI Docker Image'
    waitFor: ['-']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PROFILE=claude_vertexai'
      - '--build-arg'
      - 'GCP_PROJECT=$PROJECT_ID'
      - '--target'
      - 'app-image'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:claude_vertexai'
      - '.'
    id: 'Build Claude on VertexAI Docker Image'
    waitFor: ['-']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:claudeapi'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:claude_vertexai'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO_NAME}/${_SERVICE_NAME}:gemini'

# Substitutions - these can be set in the Cloud Build trigger
# or passed during a manual build (which is what the terraform local-exec does)
substitutions:
  _SERVICE_NAME: 'spring-boot-app' # Default value
  _REGION: 'us-central1' # Default value
  _ARTIFACT_REGISTRY_REPO_NAME: 'spring-boot-app-images' # Default value

options:
  logging: CLOUD_LOGGING_ONLY
