# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kubectl create namespace twistlock

kubectl label namespace twistlock istio-injection- istio.io/rev=asm-173-6 --overwrite

if [[ ! -f ./twistcli || $(./twistcli --version) != *"20.09.366"* ]]; then curl --progress-bar -L -k --header "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoid2FoZWVkYnJvd25AZ29vZ2xlLmNvbSIsInJvbGUiOiJhZG1pbiIsImdyb3VwcyI6bnVsbCwic2Vzc2lvblRpbWVvdXRTZWMiOjUwOCwic2Fhc1Rva2VuIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKelpYSjJhV05sVlhOaFoyVlBibXg1SWpwMGNuVmxMQ0ptYVhKemRFeHZaMmx1SWpwbVlXeHpaU3dpYVhOeklqb2lhSFIwY0hNNkx5OWhjR2t6TG5CeWFYTnRZV05zYjNWa0xtbHZJaXdpY21WemRISnBZM1FpT2pBc0luVnpaWEpTYjJ4bFZIbHdaVTVoYldVaU9pSlRlWE4wWlcwZ1FXUnRhVzRpTENKcGMxTlRUMU5sYzNOcGIyNGlPbVpoYkhObExDSnNZWE4wVEc5bmFXNVVhVzFsSWpveE5qQTNOekE0TVRZMU1UazJMQ0oxYzJWeVVtOXNaVlI1Y0dWSlpDSTZNU3dpYzJWc1pXTjBaV1JEZFhOMGIyMWxjazVoYldVaU9pSkhiMjluYkdVc0lFeE1ReUF0SURNeE1EazNNRGsxTWpVd01ERTFOelEyTWpraUxDSnpaWE56YVc5dVZHbHRaVzkxZENJNk16QXNJblZ6WlhKU2IyeGxTV1FpT2lJell6RmhNbVk0TXkwMU9EWmpMVFF4TWpRdE9HTTVZUzB4WmpSbE1XVmtaakk1TVRnaUxDSm9ZWE5FWldabGJtUmxjbEJsY20xcGMzTnBiMjV6SWpwMGNuVmxMQ0psZUhBaU9qRTJNRGMzTURreU1EY3NJblZ6WlhKdVlXMWxJam9pZDJGb1pXVmtZbkp2ZDI1QVoyOXZaMnhsTG1OdmJTSXNJblZ6WlhKU2IyeGxUbUZ0WlNJNklsTjVjM1JsYlNCQlpHMXBiaUo5LjVQeEE1ZjlYTXN4bUhEVEV4MVQ0LXB4UmM3bTdNb3NIVVROMlJhUEtzdmciLCJleHAiOjE2MDc3MTIyOTksImlzcyI6InR3aXN0bG9jayJ9.NZ7xLvOuiEq6HeNS8RIsYWAph6zRZzPkr_-auKUoUXA" https://us-west1.cloud.twistlock.com/us-3-159237196/api/v1/util/twistcli > twistcli; chmod +x twistcli; fi; ./twistcli defender install kubernetes --namespace twistlock --monitor-service-accounts --token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoid2FoZWVkYnJvd25AZ29vZ2xlLmNvbSIsInJvbGUiOiJhZG1pbiIsImdyb3VwcyI6bnVsbCwic2Vzc2lvblRpbWVvdXRTZWMiOjUwOCwic2Fhc1Rva2VuIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKelpYSjJhV05sVlhOaFoyVlBibXg1SWpwMGNuVmxMQ0ptYVhKemRFeHZaMmx1SWpwbVlXeHpaU3dpYVhOeklqb2lhSFIwY0hNNkx5OWhjR2t6TG5CeWFYTnRZV05zYjNWa0xtbHZJaXdpY21WemRISnBZM1FpT2pBc0luVnpaWEpTYjJ4bFZIbHdaVTVoYldVaU9pSlRlWE4wWlcwZ1FXUnRhVzRpTENKcGMxTlRUMU5sYzNOcGIyNGlPbVpoYkhObExDSnNZWE4wVEc5bmFXNVVhVzFsSWpveE5qQTNOekE0TVRZMU1UazJMQ0oxYzJWeVVtOXNaVlI1Y0dWSlpDSTZNU3dpYzJWc1pXTjBaV1JEZFhOMGIyMWxjazVoYldVaU9pSkhiMjluYkdVc0lFeE1ReUF0SURNeE1EazNNRGsxTWpVd01ERTFOelEyTWpraUxDSnpaWE56YVc5dVZHbHRaVzkxZENJNk16QXNJblZ6WlhKU2IyeGxTV1FpT2lJell6RmhNbVk0TXkwMU9EWmpMVFF4TWpRdE9HTTVZUzB4WmpSbE1XVmtaakk1TVRnaUxDSm9ZWE5FWldabGJtUmxjbEJsY20xcGMzTnBiMjV6SWpwMGNuVmxMQ0psZUhBaU9qRTJNRGMzTURreU1EY3NJblZ6WlhKdVlXMWxJam9pZDJGb1pXVmtZbkp2ZDI1QVoyOXZaMnhsTG1OdmJTSXNJblZ6WlhKU2IyeGxUbUZ0WlNJNklsTjVjM1JsYlNCQlpHMXBiaUo5LjVQeEE1ZjlYTXN4bUhEVEV4MVQ0LXB4UmM3bTdNb3NIVVROMlJhUEtzdmciLCJleHAiOjE2MDc3MTIyOTksImlzcyI6InR3aXN0bG9jayJ9.NZ7xLvOuiEq6HeNS8RIsYWAph6zRZzPkr_-auKUoUXA --address https://us-west1.cloud.twistlock.com/us-3-159237196 --cluster-address us-west1.cloud.twistlock.com
