# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
  - name: python
    args:
      - '-c'
      - |
        python3 -m pip install --upgrade pip  
        python3 -m pip install -r scripts/requirements.txt 
        yamllint -s -c .yamllint . 
    dir: /workspace/tools/custom-organization-policy-library
    entrypoint: bash
  - name: python
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y make git curl wget
        python3 -m pip install --upgrade pip  
        python3 -m pip install -r scripts/requirements.txt 
        mkdir local-bin/ 
        curl -L https://carvel.dev/install.sh | K14SIO_INSTALL_BIN_DIR=local-bin bash
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O local-bin/yq
        chmod +x local-bin/yq
        export PATH=$${PWD}/local-bin/:$${PATH}   
        ytt version   
        yq --version
        yq -i '.organization = "$_ORGANIZATION"' values.yaml  
        yq -i '.deployment.parent = "$_DEPLOYMENT_PARENT"' values.yaml  
        make build
    dir: /workspace/tools/custom-organization-policy-library
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y make
        make deploy-constraints
    dir: /workspace/tools/custom-organization-policy-library
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y make
        make deploy-policies
    dir: /workspace/tools/custom-organization-policy-library
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip  
        python3 -m pip install -r requirements.txt 
        export PROJECT_ID="$_PROJECT_ID"
        export PROJECT_NUMBER="$_PROJECT_NUMBER"
        export PREFIX="$_PREFIX"
        set +e
        pytest main.py --html=${SHORT_SHA}_report.html $_PYTEST_ARGS
        PYTEST_EXIT_CODE=$$?
        set -e
        if [ $$PYTEST_EXIT_CODE -eq 0 ]; then
          echo "✅ No error during running test"
        else
          echo "⚠️ Error during running tests"
        fi
        exit 0
    dir: /workspace/tools/custom-organization-policy-library/tests
    entrypoint: bash
    timeout: '10800s'
logsBucket: '$_BUCKET_BUILD/logs/'
artifacts:
  objects:
    location: '$_BUCKET_BUILD/tests/'
    paths:
      - 'tools/custom-organization-policy-library/tests/${SHORT_SHA}_report.html'
timeout: '10800s'
substitutions:
    _BUCKET_BUILD: gs://custom-org-policy-library-build
    _PYTEST_ARGS: ""
