# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/flutter:master',
    '--build-arg', 'channel=master',
  ]

- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/flutter:beta',
    '--build-arg', 'channel=beta',
  ]

- name: 'docker:stable'
  args: [
    'build', '.',
    '-t', 'gcr.io/$PROJECT_ID/flutter:stable',
    '-t', 'gcr.io/$PROJECT_ID/flutter',
    '--build-arg', 'channel=stable',
  ]

- name: 'gcr.io/$PROJECT_ID/flutter'
  args: ['--help']

timeout: '1200s'

images: [
  'gcr.io/$PROJECT_ID/flutter:master',
  'gcr.io/$PROJECT_ID/flutter:dev',
  'gcr.io/$PROJECT_ID/flutter:beta',
  'gcr.io/$PROJECT_ID/flutter:stable',
  'gcr.io/$PROJECT_ID/flutter',
]
tags: ['cloud-builders-community']
